//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LNPopupItem, NSString;

@protocol _LNPopupItemDelegate <NSObject>
- (void)_popupItem:(LNPopupItem *)arg1 didChangeValueForKey:(NSString *)arg2;
@end

