//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIToolbar.h"

@interface _LNPopupToolbar : UIToolbar
{
}

- (void)setSemanticContentAttribute:(long long)arg1;
- (void)_deepSetSemanticContentAttribute:(long long)arg1 toView:(id)arg2 startingFromView:(id)arg3;
- (void)layoutSubviews;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;

@end

