//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSURL, UIActivityIndicatorView;

@interface ANEMWebImageButton : UIButton
{
    NSURL *_imageURL;
    double _imageScale;
    UIActivityIndicatorView *_loadingIndicator;
}

@property(nonatomic) double imageScale; // @synthesize imageScale=_imageScale;
@property(retain, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)loadImage;
- (void)stopLoading;
- (id)initWithFrame:(struct CGRect)arg1;

@end

