//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class NSURL, UIActivityIndicatorView;

@interface ANEMWebImageView : UIImageView
{
    NSURL *_imageURL;
    UIActivityIndicatorView *_loadingIndicator;
}

@property(retain, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)loadImage;
- (id)initWithFrame:(struct CGRect)arg1;

@end

