//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface APTWrapper : NSObject
{
}

+ (void)performOperationsForInstalls:(id)arg1 removals:(id)arg2 progressCallback:(CDUnknownBlockType)arg3 outputCallback:(CDUnknownBlockType)arg4 completionCallback:(CDUnknownBlockType)arg5;
+ (_Bool)verifySignatureForKey:(id)arg1 data:(id)arg2 error:(id *)arg3;
+ (double)installProgressFromAPTStatus:(id)arg1 statusValid:(_Bool *)arg2 statusReadable:(id *)arg3;
+ (id)packageOperationsForInstalls:(id)arg1 removals:(id)arg2 error:(id *)arg3;

@end

