//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

@class SettingsHeaderContainerView;

@interface BaseSettingsViewController : UITableViewController
{
    SettingsHeaderContainerView *headerContainerView;
}

- (void).cxx_destruct;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)setHeaderView:(id)arg1;
- (id)headerView;
- (void)scrollViewDidScroll:(id)arg1;
- (id)reusableCellWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 cellClass:(Class)arg3;
- (id)reusableCellWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)setTitleViewAlpha:(double)arg1;
- (void)layoutHeader;
- (void)dismiss;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

