//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSString, NSURL, PackageIconView, SourceProgressIndicatorView, UIImage;

@interface BaseSubtitleTableViewCell : UITableViewCell
{
    PackageIconView *iconView;
    SourceProgressIndicatorView *progressView;
    NSURL *iconURL;
    NSString *_title;
    NSString *_subtitle;
    UIImage *_icon;
    double _progress;
}

@property(nonatomic) double progress; // @synthesize progress=_progress;
@property(retain, nonatomic) UIImage *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)loadIconFromURL:(id)arg1 placeholderIcon:(id)arg2;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

