//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "UIViewControllerPreviewingDelegate.h"

@class FeaturedBannersView, NSArray, NSDictionary, NSMutableDictionary, NSString, PaymentAuthenticationBannerView, Repo, UIStackView;

@interface CategoryViewController : UITableViewController <UIViewControllerPreviewingDelegate>
{
    NSArray *_categories;
    NSMutableDictionary *_categoriesCountCache;
    NSDictionary *featuredBannerData;
    FeaturedBannersView *bannersView;
    UIStackView *headerStackView;
    PaymentAuthenticationBannerView *authenticationBannerView;
    Repo *_repoContext;
}

@property(retain, nonatomic) Repo *repoContext; // @synthesize repoContext=_repoContext;
- (void).cxx_destruct;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)controllerForIndexPath:(id)arg1;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)loadIdentifierForCategoryAtIndexPath:(id)arg1;
- (id)categoryNameAtIndexPath:(id)arg1;
- (_Bool)isAllCategoriesIndexPath:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)updateHeaderStackViewWithParentSize:(struct CGSize)arg1;
- (void)updateHeaderStackView;
- (void)reloadData;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

