//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CSSSelector.h"

@class NSString;

@interface CSSAttributeSelector : CSSSelector
{
    unsigned long long _type;
    NSString *_name;
    NSString *_value;
}

+ (id)hasAttributeSelector:(id)arg1;
+ (id)idSelector:(id)arg1;
+ (id)classSelector:(id)arg1;
@property(readonly, nonatomic) NSString *value; // @synthesize value=_value;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) unsigned long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)debugDescription;
- (_Bool)acceptElement:(id)arg1;
- (id)initWithType:(unsigned long long)arg1 attributeName:(id)arg2 attrbiuteValue:(id)arg3;

@end

