//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HTMLInputStreamReader.h"

@interface CSSInputStream : HTMLInputStreamReader
{
}

- (id)consumeCombinator;
- (unsigned int)consumeEscapedCodePoint;
- (id)consumeStringWithEndingCodePoint:(unsigned int)arg1;
- (id)consumeIdentifier;
- (void)consumeWhitespace;

@end

