//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CSSSelector.h"

@class NSString;

@interface CSSPseudoClassSelector : CSSSelector
{
    NSString *_className;
    CSSSelector *_selector;
}

@property(readonly, nonatomic) NSString *className; // @synthesize className=_className;
- (void).cxx_destruct;
- (id)description;
- (id)debugDescription;
- (_Bool)acceptElement:(id)arg1;
- (id)initWithClassName:(id)arg1 selector:(id)arg2;

@end

