//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CSSSelector.h"

@interface CSSPseudoFunctionSelector : CSSSelector
{
    CSSSelector *_selector;
}

+ (id)hasSelector:(id)arg1;
+ (id)notSelector:(id)arg1;
@property(readonly, nonatomic) CSSSelector *selector; // @synthesize selector=_selector;
- (void).cxx_destruct;
- (id)initWithSelector:(id)arg1;

@end

