//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CSSSelector.h"

@class NSString;

@interface CSSSelectorBlock : CSSSelector
{
    NSString *_name;
    CDUnknownBlockType _acceptBlock;
}

- (void).cxx_destruct;
- (id)debugDescription;
- (_Bool)acceptElement:(id)arg1;
- (id)initWithName:(id)arg1 block:(CDUnknownBlockType)arg2;

@end

