//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CSTextRenderView, NSAttributedString;

@interface CSTextView : UIView
{
    CSTextRenderView *_renderView;
    UIView *_overlayView;
}

@property(readonly, nonatomic) UIView *overlayView; // @synthesize overlayView=_overlayView;
- (void).cxx_destruct;
- (_Bool)processAction:(id)arg1;
- (void)setBackgroundColor:(id)arg1;
@property(retain, nonatomic) NSAttributedString *attributedText;
- (id)initWithFrame:(struct CGRect)arg1;

@end

