//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWebView.h"

@interface CydiaAccountUIWebView : UIWebView
{
}

- (id)webThreadWebView:(id)arg1 resource:(id)arg2 willSendRequest:(id)arg3 redirectResponse:(id)arg4 fromDataSource:(id)arg5;
- (void)setKeysOnMutableURLRequest:(id)arg1;
- (void)loadRequest:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

