//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DepictionBaseView.h"

@class NSString, UIButton;

@interface DepictionButtonView : DepictionBaseView
{
    UIButton *_button;
    NSString *_action;
    NSString *_backupAction;
    double _yPadding;
    _Bool _openExternal;
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (_Bool)processAction:(id)arg1;
- (void)buttonTapped:(id)arg1;
- (double)depictionHeightForWidth:(double)arg1;
- (id)initWithDictionary:(id)arg1 viewController:(id)arg2 tintColor:(id)arg3;

@end

