//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DepictionBaseView.h"

#import "UIGestureRecognizerDelegate.h"

@class NSString, UIImageView, UILabel, UIView;

@interface DepictionTableButtonView : DepictionBaseView <UIGestureRecognizerDelegate>
{
    UIView *_selectionView;
    UILabel *_titleLabel;
    UIImageView *_chevronView;
    NSString *_action;
    NSString *_backupAction;
    _Bool _openExternal;
}

- (void).cxx_destruct;
- (_Bool)processAction:(id)arg1;
- (void)buttonTapped:(id)arg1;
- (_Bool)accessibilityActivate;
- (void)layoutSubviews;
- (double)depictionHeightForWidth:(double)arg1;
- (id)initWithDictionary:(id)arg1 viewController:(id)arg2 tintColor:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

