//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DepictionBaseView.h"

@class AVPlayer, AVPlayerLooper, AVPlayerViewController, UIView;

@interface DepictionVideoView : DepictionBaseView
{
    long long _alignment;
    AVPlayer *_player;
    AVPlayerViewController *_playerViewController;
    AVPlayerLooper *_playerLooper;
    UIView *_videoView;
    double _width;
    double _height;
    double _cornerRadius;
    _Bool _autoPlayEnabled;
    _Bool _showPlaybackControls;
    _Bool _loopEnabled;
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (double)depictionHeightForWidth:(double)arg1;
- (id)initWithDictionary:(id)arg1 viewController:(id)arg2 tintColor:(id)arg3;

@end

