//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DepictionBaseView.h"

#import "UIScrollViewDelegate.h"

@class AVPlayer, AVPlayerViewController, NSDictionary, NSMutableArray, NSString, UIScrollView;

@interface DepictionScreenshotsView : DepictionBaseView <UIScrollViewDelegate>
{
    NSDictionary *_depiction;
    UIScrollView *_scrollView;
    struct CGSize _itemSize;
    double _itemCornerRadius;
    NSMutableArray *_screenshotViews;
    AVPlayer *_player;
    AVPlayerViewController *_playerViewController;
    _Bool _isPaging;
}

- (void).cxx_destruct;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollToPageIndex:(long long)arg1 animated:(_Bool)arg2;
- (double)contentOffsetForPageIndex:(long long)arg1;
- (long long)currentPageIndex;
- (long long)pageIndexForContentOffset:(double)arg1;
- (double)viewSegmentWidth;
- (void)layoutSubviews;
- (void)fullScreenImage:(id)arg1;
- (double)fullViewHeight;
- (double)depictionHeightForWidth:(double)arg1;
- (id)initWithDictionary:(id)arg1 viewController:(id)arg2 tintColor:(id)arg3 isPaging:(_Bool)arg4;
- (id)initWithDictionary:(id)arg1 viewController:(id)arg2 tintColor:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

