//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DepictionBaseView.h"

@class CSTextView, NSMutableAttributedString;

@interface DepictionMarkdownView : DepictionBaseView
{
    NSMutableAttributedString *_attributedString;
    _Bool _useSpacing;
    _Bool _useHalfSpacing;
    _Bool _useMargins;
    _Bool _useRawFormat;
    _Bool _heightRequested;
    CSTextView *_textView;
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (_Bool)processAction:(id)arg1;
- (double)depictionHeightForWidth:(double)arg1;
- (id)initWithDictionary:(id)arg1 viewController:(id)arg2 tintColor:(id)arg3;

@end

