//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class DepictionBaseView, NSURL, UIActivityIndicatorView, UIScrollView;

@interface DepictionSubpageViewController : UIViewController
{
    UIScrollView *_scrollView;
    DepictionBaseView *_depictionView;
    UIActivityIndicatorView *loadingView;
    NSURL *_depictionURL;
}

@property(retain, nonatomic) NSURL *depictionURL; // @synthesize depictionURL=_depictionURL;
- (void).cxx_destruct;
- (void)viewDidLayoutSubviews;
- (void)subviewHeightChanged;
- (void)versionTooLow;
- (void)reloadData;
- (void)viewDidLoad;

@end

