//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DepictionBaseView.h"

#import "GADBannerViewDelegate.h"

@class GADBannerView, NSString;

@interface DepictionAdmobView : DepictionBaseView <GADBannerViewDelegate>
{
    GADBannerView *_bannerView;
}

- (void).cxx_destruct;
- (void)adView:(id)arg1 didFailToReceiveAdWithError:(id)arg2;
- (void)adViewDidReceiveAd:(id)arg1;
- (void)layoutSubviews;
- (double)depictionHeightForWidth:(double)arg1;
- (id)initWithDictionary:(id)arg1 viewController:(id)arg2 tintColor:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

