//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XLFormViewController.h"

@class NSString, NSURL, UIActivityIndicatorView, UIBarButtonItem;

@interface DepictionFormViewController : XLFormViewController
{
    NSString *_formAction;
    UIActivityIndicatorView *loadingView;
    UIBarButtonItem *submitBarButtonItem;
    NSURL *_formURL;
}

@property(retain, nonatomic) NSURL *formURL; // @synthesize formURL=_formURL;
- (void).cxx_destruct;
- (void)submit:(id)arg1;
- (void)dismiss:(id)arg1;
- (void)populateRowsOfSection:(id)arg1 rawSection:(id)arg2;
- (void)populateSectionsOfForm:(id)arg1 rawForm:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)populateNavigationBar:(id)arg1;
- (void)presentErrorDialogWithMessage:(id)arg1 mustCancel:(_Bool)arg2;
- (void)viewDidLoad;

@end

