//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "DepictionViewDelegate.h"

@class DepictionScreenshotsView, NSDictionary, UIColor;

@interface DepictionScreenshotsViewController : UIViewController <DepictionViewDelegate>
{
    DepictionScreenshotsView *_screenshotsView;
    NSDictionary *_depiction;
    UIColor *_tintColor;
}

@property(retain, nonatomic) UIColor *tintColor; // @synthesize tintColor=_tintColor;
@property(retain, nonatomic) NSDictionary *depiction; // @synthesize depiction=_depiction;
- (void).cxx_destruct;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)dismiss:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)subviewHeightChanged;
- (void)viewDidLoad;
- (void)loadView;

@end

