//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DepictionBaseView.h"

@class NSMutableArray, UIView;

@interface DepictionTabView : DepictionBaseView
{
    NSMutableArray *_tabViews;
    NSMutableArray *_tabContentViews;
    UIView *_tabView;
    UIView *_tabViewSeparator;
    UIView *_tabViewHighlight;
    long long _activeTab;
}

@property(nonatomic) long long activeTab; // @synthesize activeTab=_activeTab;
- (void).cxx_destruct;
- (double)depictionHeightForWidth:(double)arg1;
- (void)subviewHeightChanged;
- (void)tabTapped:(id)arg1;
- (void)layoutSubviews;
- (id)initWithDictionary:(id)arg1 viewController:(id)arg2 tintColor:(id)arg3;

@end

