//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DFContinuousForceTouchGestureRecognizer;

@protocol DFContinuousForceTouchDelegate <NSObject>
- (void)forceTouchRecognized:(DFContinuousForceTouchGestureRecognizer *)arg1;

@optional
- (void)forceTouchDidTimeout:(DFContinuousForceTouchGestureRecognizer *)arg1;
- (void)forceTouchRecognizer:(DFContinuousForceTouchGestureRecognizer *)arg1 didEndWithForce:(double)arg2 maxForce:(double)arg3;
- (void)forceTouchRecognizer:(DFContinuousForceTouchGestureRecognizer *)arg1 didCancelWithForce:(double)arg2 maxForce:(double)arg3;
- (void)forceTouchRecognizer:(DFContinuousForceTouchGestureRecognizer *)arg1 didMoveWithForce:(double)arg2 maxForce:(double)arg3;
- (void)forceTouchRecognizer:(DFContinuousForceTouchGestureRecognizer *)arg1 didStartWithForce:(double)arg2 maxForce:(double)arg3;
@end

