//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADNInterstitial.h"

@class GADNCorrelator, NSString;

@interface DFPNInterstitial : GADNInterstitial
{
    id <DFPCustomRenderedInterstitialDelegate> _customRenderedInterstitialDelegate;
}

@property(nonatomic) __weak id <DFPCustomRenderedInterstitialDelegate> customRenderedInterstitialDelegate; // @synthesize customRenderedInterstitialDelegate=_customRenderedInterstitialDelegate;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy, nonatomic) NSString *adUnitID; // @dynamic adUnitID;
@property(nonatomic) __weak id <GADAppEventDelegate> appEventDelegate; // @dynamic appEventDelegate;
@property(retain, nonatomic) GADNCorrelator *correlator; // @dynamic correlator;

@end

