//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL;

@interface DFPNCustomRenderedAd : NSObject
{
}

- (void)finishedRenderingAdView:(id)arg1;
- (void)recordImpression;
- (void)recordClick;
@property(readonly, copy, nonatomic) NSURL *adBaseURL;
@property(readonly, copy, nonatomic) NSString *adHTML;

@end

