//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADNBannerView.h"

@class GADNCorrelator, GADNVideoController, NSArray, NSString;

@interface DFPNBannerView : GADNBannerView
{
    id <DFPCustomRenderedBannerViewDelegate> _customRenderedBannerViewDelegate;
}

@property(nonatomic) __weak id <DFPCustomRenderedBannerViewDelegate> customRenderedBannerViewDelegate; // @synthesize customRenderedBannerViewDelegate=_customRenderedBannerViewDelegate;
- (void).cxx_destruct;
- (void)setAdOptions:(id)arg1;
- (void)recordImpression;
- (void)resize:(struct GADNAdSize)arg1;

// Remaining properties
@property(nonatomic) __weak id <GADAdSizeDelegate> adSizeDelegate; // @dynamic adSizeDelegate;
@property(copy, nonatomic) NSString *adUnitID; // @dynamic adUnitID;
@property(nonatomic) __weak id <GADAppEventDelegate> appEventDelegate; // @dynamic appEventDelegate;
@property(retain, nonatomic) GADNCorrelator *correlator; // @dynamic correlator;
@property(nonatomic) _Bool enableManualImpressions; // @dynamic enableManualImpressions;
@property(copy, nonatomic) NSArray *validAdSizes; // @dynamic validAdSizes;
@property(readonly, nonatomic) GADNVideoController *videoController; // @dynamic videoController;

@end

