//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseSubtitleTableViewCell.h"

@class Download, NSString, Package;

@interface DownloadsTableViewCell : BaseSubtitleTableViewCell
{
    _Bool _shouldHaveDownload;
    Package *_package;
    Download *_download;
    NSString *_errorDescription;
}

@property(nonatomic) _Bool shouldHaveDownload; // @synthesize shouldHaveDownload=_shouldHaveDownload;
@property(retain, nonatomic) NSString *errorDescription; // @synthesize errorDescription=_errorDescription;
@property(retain, nonatomic) Download *download; // @synthesize download=_download;
@property(retain, nonatomic) Package *package; // @synthesize package=_package;
- (void).cxx_destruct;
- (void)prepareForReuse;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

