//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DownloadsTableViewController, NSArray, NSMutableArray, NSMutableDictionary;

@interface DownloadManager : NSObject
{
    NSMutableArray *_upgrades;
    NSMutableArray *_installations;
    NSMutableArray *_uninstallations;
    NSMutableArray *_installdeps;
    NSMutableArray *_uninstalldeps;
    NSMutableArray *_errors;
    NSMutableDictionary *_queued;
    NSMutableArray *_queuedRemovals;
    NSMutableArray *_confirmedRemovals;
    NSMutableDictionary *_downloads;
    long long _queueLockCount;
    struct _opaque_pthread_mutex_t _queueLock;
    NSMutableDictionary *_repoDownloadOverrideProviders;
    _Bool _lockedForInstallation;
    float _totalProgress;
    DownloadsTableViewController *_viewController;
}

+ (id)sharedInstance;
@property(readonly, nonatomic) NSArray *errors; // @synthesize errors=_errors;
@property(readonly, nonatomic) NSArray *uninstalldeps; // @synthesize uninstalldeps=_uninstalldeps;
@property(readonly, nonatomic) NSArray *installdeps; // @synthesize installdeps=_installdeps;
@property(readonly, nonatomic) NSArray *uninstallations; // @synthesize uninstallations=_uninstallations;
@property(readonly, nonatomic) NSArray *installations; // @synthesize installations=_installations;
@property(readonly, nonatomic) NSArray *upgrades; // @synthesize upgrades=_upgrades;
@property(retain, nonatomic) DownloadsTableViewController *viewController; // @synthesize viewController=_viewController;
@property(nonatomic) float totalProgress; // @synthesize totalProgress=_totalProgress;
@property(nonatomic) _Bool lockedForInstallation; // @synthesize lockedForInstallation=_lockedForInstallation;
- (void).cxx_destruct;
- (void)overrideDownloadURLForPackage:(id)arg1 fromRepo:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)deregisterDownloadOverrideProvider:(id)arg1;
- (void)deregisterDownloadOverrideProvider:(id)arg1 forRepo:(id)arg2;
- (void)registerDownloadOverrideProvider:(id)arg1 forRepo:(id)arg2;
- (void)unlockQueue;
- (void)lockQueue;
- (void)removeObject:(id)arg1 fromQueue:(int)arg2;
- (void)addObject:(id)arg1 toQueue:(int)arg2;
- (int)findPackage:(id)arg1;
- (void)removePackage:(id)arg1;
- (void)reloadData:(_Bool)arg1;
- (void)removeAllItems;
- (void)addBrokenPackages;
- (void)recheckTotalOps;
- (_Bool)verifyAndMoveDownload:(id)arg1 withFile:(id)arg2 errorstr:(id *)arg3;
- (_Bool)verifyAlreadyDownloaded:(id)arg1;
- (id)downloadForPackage:(id)arg1;
- (void)startUnqueuedDownloads;
- (void)cancelUnqueuedDownloads;
- (void)addDownloadItemsIfNotPresent;
- (long long)uninstallingPackages;
- (long long)readyPackages;
- (long long)queuedPackages;
- (long long)downloadingPackages;
- (id)init;

@end

