//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DpkgWrapper : NSObject
{
}

+ (id)installPackageAtURL:(id)arg1;
+ (id)rawFieldsForPackageAtURL:(id)arg1;
+ (void)ignoreUpdates:(_Bool)arg1 forPackage:(id)arg2;
+ (_Bool)getValuesForStatusField:(id)arg1 wantInfo:(int *)arg2 eFlag:(int *)arg3 status:(int *)arg4;
+ (_Bool)isVersion:(id)arg1 greaterThan:(id)arg2;
+ (id)getArchitectures;
+ (_Bool)dpkgInterrupted;

@end

