//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FCModelCachedObject : NSObject
{
    _Bool _currentResultIsValid;
    Class _modelClass;
    CDUnknownBlockType _generator;
    id _currentResult;
}

+ (id)objectWithModelClass:(Class)arg1 cacheIdentifier:(id)arg2 generator:(CDUnknownBlockType)arg3;
+ (void)clearCache;
@property(retain, nonatomic) id currentResult; // @synthesize currentResult=_currentResult;
@property(nonatomic) _Bool currentResultIsValid; // @synthesize currentResultIsValid=_currentResultIsValid;
@property(copy, nonatomic) CDUnknownBlockType generator; // @synthesize generator=_generator;
@property(retain, nonatomic) Class modelClass; // @synthesize modelClass=_modelClass;
- (void).cxx_destruct;
@property(readonly) id value;
- (void)flush:(id)arg1;
- (void)dealloc;

@end

