//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FCModelFieldInfo : NSObject
{
    _Bool _nullAllowed;
    long long _type;
    id _defaultValue;
    Class _propertyClass;
}

@property(retain, nonatomic) Class propertyClass; // @synthesize propertyClass=_propertyClass;
@property(retain, nonatomic) id defaultValue; // @synthesize defaultValue=_defaultValue;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) _Bool nullAllowed; // @synthesize nullAllowed=_nullAllowed;
- (void).cxx_destruct;
- (id)description;

@end

