//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperationQueue.h"

@class FMDatabase, NSString;

@interface FCModelDatabaseQueue : NSOperationQueue
{
    FMDatabase *_openDatabase;
    NSString *_path;
}

@property(retain, nonatomic) NSString *path; // @synthesize path=_path;
@property(retain, nonatomic) FMDatabase *openDatabase; // @synthesize openDatabase=_openDatabase;
- (void).cxx_destruct;
- (void)inDatabase:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (void)close;
- (void)execOnSelfSync:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) FMDatabase *database;
- (id)initWithDatabasePath:(id)arg1;

@end

