//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FCModelCachedObject;

@interface FCModelLiveResultArray : NSObject
{
    FCModelCachedObject *_cachedObject;
}

+ (id)arrayWithModelClass:(Class)arg1 queryAfterWHERE:(id)arg2 arguments:(id)arg3;
@property(retain, nonatomic) FCModelCachedObject *cachedObject; // @synthesize cachedObject=_cachedObject;
- (void).cxx_destruct;
- (id)allObjects;

@end

