//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FeaturedBaseView.h"

#import "FeaturedBannerViewPreview.h"

@class NSMutableArray, UIScrollView, UIStackView;

@interface FeaturedBannersView : FeaturedBaseView <FeaturedBannerViewPreview>
{
    UIScrollView *_scrollView;
    UIStackView *_stackView;
    struct CGSize _itemSize;
    NSMutableArray *_bannerViews;
}

- (void).cxx_destruct;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (void)bannerTapped:(id)arg1;
- (id)viewControllerForBanner:(id)arg1;
- (double)depictionHeightForWidth:(double)arg1;
- (id)initWithDictionary:(id)arg1 viewController:(id)arg2;

@end

