//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

#import "UIViewControllerPreviewingDelegate.h"

@class NSDictionary, NSObject<FeaturedBannerViewPreview>, NSString, UIImageView, UILabel, UIView;

@interface FeaturedBannerView : UIButton <UIViewControllerPreviewingDelegate>
{
    UIView *_darkeningView;
    UIView *_highlightView;
    UIImageView *_bannerImageView;
    UILabel *_bannerTitleLabel;
    NSObject<FeaturedBannerViewPreview> *_previewDelegate;
    NSDictionary *_banner;
}

@property(retain, nonatomic) NSDictionary *banner; // @synthesize banner=_banner;
@property(nonatomic) __weak NSObject<FeaturedBannerViewPreview> *previewDelegate; // @synthesize previewDelegate=_previewDelegate;
- (void).cxx_destruct;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint)arg2;
- (void)setHighlighted:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

