//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FeaturedBaseView.h"

@class UIView;

@interface FeaturedSeparatorView : FeaturedBaseView
{
    UIView *_separatorView;
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (double)depictionHeightForWidth:(double)arg1;
- (id)initWithDictionary:(id)arg1 viewController:(id)arg2;

@end

