//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FeaturedBaseView.h"

@class UILabel;

@interface FeaturedHeaderView : FeaturedBaseView
{
    UILabel *_headerLabel;
    double _yPadding;
    double _xPadding;
    _Bool _useMargins;
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (double)depictionHeightForWidth:(double)arg1;
- (id)initWithDictionary:(id)arg1 viewController:(id)arg2;

@end

