//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIScrollViewDelegate.h"

@class NSLayoutConstraint, NSString, UIButton, UILabel, UIScrollView, UIView;

@interface FlaggedSourceWarningViewController : UIViewController <UIScrollViewDelegate>
{
    CDUnknownBlockType _addFlaggedRepoAnyway;
    UILabel *_titleLabel;
    UILabel *_bodyLabel;
    UIButton *_safetyButton;
    UIButton *_continueButton;
    UIScrollView *_scrollView;
    UIView *_scrollHairlineView;
    NSLayoutConstraint *_scrollHairlineHeightConstraint;
}

@property(nonatomic) __weak NSLayoutConstraint *scrollHairlineHeightConstraint; // @synthesize scrollHairlineHeightConstraint=_scrollHairlineHeightConstraint;
@property(nonatomic) __weak UIView *scrollHairlineView; // @synthesize scrollHairlineView=_scrollHairlineView;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak UIButton *continueButton; // @synthesize continueButton=_continueButton;
@property(nonatomic) __weak UIButton *safetyButton; // @synthesize safetyButton=_safetyButton;
@property(nonatomic) __weak UILabel *bodyLabel; // @synthesize bodyLabel=_bodyLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(copy, nonatomic) CDUnknownBlockType addFlaggedRepoAnyway; // @synthesize addFlaggedRepoAnyway=_addFlaggedRepoAnyway;
- (void).cxx_destruct;
- (void)scrollViewDidScroll:(id)arg1;
- (void)determineScrollHairlineAnimated:(_Bool)arg1;
- (void)addAnywayButtonTapped:(id)arg1;
- (void)safetyButtonTapped:(id)arg1;
- (void)addAnyway;
- (void)presentLastChanceAlert;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

