//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADNAdLoader, GADNRequestError;

@protocol GADAdLoaderDelegate <NSObject>
- (void)adLoader:(GADNAdLoader *)arg1 didFailToReceiveAdWithError:(GADNRequestError *)arg2;

@optional
- (void)adLoaderDidFinishLoading:(GADNAdLoader *)arg1;
@end

