//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADNCustomEventRequest, NSString;

@protocol GADCustomEventBanner <NSObject>
@property(nonatomic) __weak id <GADCustomEventBannerDelegate> delegate;
- (void)requestBannerAd:(struct GADNAdSize)arg1 parameter:(NSString *)arg2 label:(NSString *)arg3 request:(GADNCustomEventRequest *)arg4;
@end

