//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADOInterstitial, GADORequestError;

@protocol GADInterstitialDelegate <NSObject>

@optional
- (void)interstitialWillLeaveApplication:(GADOInterstitial *)arg1;
- (void)interstitialDidDismissScreen:(GADOInterstitial *)arg1;
- (void)interstitialWillDismissScreen:(GADOInterstitial *)arg1;
- (void)interstitialDidFailToPresentScreen:(GADOInterstitial *)arg1;
- (void)interstitialWillPresentScreen:(GADOInterstitial *)arg1;
- (void)interstitial:(GADOInterstitial *)arg1 didFailToReceiveAdWithError:(GADORequestError *)arg2;
- (void)interstitialDidReceiveAd:(GADOInterstitial *)arg1;
@end

