//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADNScheduler, GADNURLSession, GADNWebViewPinger, NSMutableSet, NSObject<OS_dispatch_queue>;

@interface GADNPinger : NSObject
{
    GADNURLSession *_pingerSession;
    GADNWebViewPinger *_webViewPinger;
    NSObject<OS_dispatch_queue> *_lockQueue;
    GADNScheduler *_retryScheduler;
    NSMutableSet *_activeRetryURLStrings;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)pingRetryURLs;
- (void)removeURLStringFromPendingRetryRequests:(id)arg1;
- (void)savePendingRetryURLStrings:(id)arg1;
- (id)pendingRetryURLStrings;
- (void)pingRetryURLInternal:(id)arg1;
- (void)storeRetryURL:(id)arg1;
- (void)pingRequest:(id)arg1 context:(id)arg2 queue:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (void)pingURL:(id)arg1 context:(id)arg2 queue:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (id)init;

@end

