//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADNEventContextSource.h"
#import "GADNMonitorOwner.h"

@class GADNEventContext, GADNRootViewControllerProvider, NSMutableArray, NSString;

@interface GADNAd : NSObject <GADNEventContextSource, GADNMonitorOwner>
{
    GADNEventContext *_context;
    NSMutableArray *_monitors;
    GADNRootViewControllerProvider *_rootViewControllerProvider;
}

@property(readonly, nonatomic) GADNRootViewControllerProvider *rootViewControllerProvider; // @synthesize rootViewControllerProvider=_rootViewControllerProvider;
- (void).cxx_destruct;
- (void)addMonitor:(id)arg1;
@property(readonly, nonatomic) GADNEventContext *context;
- (id)initWithContext:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

