//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADNAd, GADNObserverCollection, GADNWebViewController, NSObject<OS_dispatch_queue>;

@interface GADNContentSizeMonitor : NSObject
{
    GADNObserverCollection *_observers;
    GADNAd *_ad;
    GADNWebViewController *_webViewController;
    NSObject<OS_dispatch_queue> *_lockQueue;
    double _lastObservedContentHeight;
}

- (void).cxx_destruct;
- (void)updateContentHeight:(double)arg1;
- (void)updateContentHeightWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)initWithWebAdView:(id)arg1 ad:(id)arg2;

@end

