//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADNClickProtection, GADNFullScreenAdViewController, GADNSwappableView, UIView;

@interface GADNExpandActionMonitorConfiguration : NSObject
{
    _Bool _customCloseBlocked;
    _Bool _analyticsLoggingEnabled;
    GADNClickProtection *_clickProtection;
    GADNFullScreenAdViewController *_presenter;
    GADNSwappableView *_swappableView;
    UIView *_referenceView;
}

@property(readonly, nonatomic) _Bool analyticsLoggingEnabled; // @synthesize analyticsLoggingEnabled=_analyticsLoggingEnabled;
@property(readonly, nonatomic) _Bool customCloseBlocked; // @synthesize customCloseBlocked=_customCloseBlocked;
@property(nonatomic) __weak UIView *referenceView; // @synthesize referenceView=_referenceView;
@property(readonly, nonatomic) __weak GADNSwappableView *swappableView; // @synthesize swappableView=_swappableView;
@property(readonly, nonatomic) __weak GADNFullScreenAdViewController *presenter; // @synthesize presenter=_presenter;
@property(readonly, nonatomic) GADNClickProtection *clickProtection; // @synthesize clickProtection=_clickProtection;
- (void).cxx_destruct;
- (void)setCustomCloseBlocked:(_Bool)arg1;
- (id)initWithSwappableView:(id)arg1 referenceView:(id)arg2 customCloseBlocked:(_Bool)arg3 clickProtection:(id)arg4 analyticsLoggingEnabled:(_Bool)arg5;
- (id)initWithPresenter:(id)arg1 referenceView:(id)arg2 customCloseBlocked:(_Bool)arg3 clickProtection:(id)arg4 analyticsLoggingEnabled:(_Bool)arg5;

@end

