//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADNObserverCollection, UIViewController;

@interface GADNStatusBarMonitor : NSObject
{
    UIViewController *_viewController;
    GADNObserverCollection *_observers;
}

- (void).cxx_destruct;
- (void)updateStatusBar;
- (id)initWithViewController:(id)arg1;

@end

