//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADNEventContext, GADNObserverCollection, GADNSafeBrowsingReport, NSURL, UIView;

@interface GADNSafeBrowsingMonitor : NSObject
{
    GADNObserverCollection *_observers;
    GADNEventContext *_context;
    NSURL *_reportURL;
    _Bool _shouldReportMaliciousAds;
    _Bool _shouldReportBenignAds;
    GADNSafeBrowsingReport *_report;
    UIView *_adView;
}

- (void).cxx_destruct;
- (void)sendReport;
- (void)observeNotificationName:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (id)initWithAdView:(id)arg1 adRequestTransaction:(id)arg2 baseURL:(id)arg3 monitoredContext:(id)arg4 configuration:(id)arg5;

@end

