//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADNAdVideoController, GADNObserverCollection;

@interface GADNVideoMetadataMonitor : NSObject
{
    GADNObserverCollection *_observers;
    GADNAdVideoController *_videoController;
}

- (void).cxx_destruct;
- (void)handleVideoMetadataAction:(id)arg1;
- (id)initWithMessageSource:(id)arg1 adVideoController:(id)arg2;

@end

