//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADNEventContextSource.h"

@class GADNEventContext, GADNTargeting, NSDictionary, NSObject<OS_dispatch_queue>, NSString, NSURL, NSURLRequest;

@interface GADNServerRequest : NSObject <GADNEventContextSource>
{
    GADNEventContext *_context;
    NSObject<OS_dispatch_queue> *_lockQueue;
    NSDictionary *_RTBAdapters;
    GADNServerRequest *_parentServerRequest;
    GADNTargeting *_targeting;
    NSURLRequest *_URLRequest;
    NSURL *_baseURL;
    NSDictionary *_signals;
}

@property(readonly, copy, nonatomic) NSDictionary *signals; // @synthesize signals=_signals;
@property(copy, nonatomic) NSURL *baseURL; // @synthesize baseURL=_baseURL;
@property(copy, nonatomic) NSURLRequest *URLRequest; // @synthesize URLRequest=_URLRequest;
@property(retain, nonatomic) GADNTargeting *targeting; // @synthesize targeting=_targeting;
@property(retain, nonatomic) GADNServerRequest *parentServerRequest; // @synthesize parentServerRequest=_parentServerRequest;
- (void).cxx_destruct;
- (_Bool)updateAdReferences:(id *)arg1;
- (void)updateSignals;
@property(readonly, nonatomic) NSDictionary *RTBAdapters;
- (void)clearRTBAdapters;
- (void)updateRTBAdapters;
- (id)initWithContext:(id)arg1;
@property(readonly, nonatomic) GADNEventContext *context;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

