//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVAssetResourceLoaderDelegate.h"
#import "GADNAVPlayerItemProvider.h"

@class AVAssetResourceLoadingRequest, AVPlayerItem, GADNResourceBuffer, GADNVideoAssetLoader, GADNVideoConfiguration, GADNVideoPlayer, NSObject<OS_dispatch_queue>, NSString, NSTimer, NSURL;

@interface GADNAssetLoadingVideoPlayerItem : NSObject <GADNAVPlayerItemProvider, AVAssetResourceLoaderDelegate>
{
    NSURL *_videoURL;
    GADNVideoAssetLoader *_assetLoader;
    GADNVideoConfiguration *_videoConfiguration;
    AVPlayerItem *_playerItem;
    NSTimer *_playerItemCheckSourceTimer;
    _Bool _loadingEnabled;
    AVAssetResourceLoadingRequest *_loadingRequest;
    GADNResourceBuffer *_resourceBuffer;
    long long _resourceBufferStartingByteOffset;
    GADNVideoPlayer *_player;
    id _playbackProgressObserver;
    float _videoBitRateInBitsPerSecond;
    double _playerItemCachingStartTimeInterval;
    double _playerItemCurrentTimeInterval;
    long long _loadedContentSizeWithNoBufferUpdate;
    long long _numberOfFailedResourceBuffer;
    NSObject<OS_dispatch_queue> *_lockQueue;
}

- (void).cxx_destruct;
- (void)resourceLoader:(id)arg1 didCancelLoadingRequest:(id)arg2;
- (_Bool)resourceLoader:(id)arg1 shouldWaitForLoadingOfRequestedResource:(id)arg2;
- (_Bool)loadDataRequest:(id)arg1 withError:(id *)arg2;
- (_Bool)loadContentRequest:(id)arg1 withError:(id *)arg2;
- (_Bool)prepareForLoadingByteOffset:(long long)arg1;
- (void)processLoadingRequest;
- (void)handlePlayerItemUpdates;
- (void)loadPlayerItemData;
- (void)stopPlayerItemCheckSourceTimer;
- (void)startPlayerItemCheckSourceTimer;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)playerItem;
- (id)videoURL;
- (void)setPlayer:(id)arg1;
- (void)dealloc;
- (id)initWithVideoURL:(id)arg1 assetLoader:(id)arg2 videoConfiguration:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

