//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADNMonitorOwner.h"
#import "GADNPresenting.h"

@class GADNCloseButton, GADNEventContext, GADNMRAIDResizeProperties, GADNObserverCollection, NSMutableArray, NSString, UIView;

@interface GADNMRAIDResizePresenter : NSObject <GADNPresenting, GADNMonitorOwner>
{
    UIView *_contentView;
    UIView *_pivotView;
    UIView *_cropView;
    UIView *_referenceView;
    _Bool _relinquishCalled;
    GADNObserverCollection *_observers;
    NSMutableArray *_monitors;
    GADNEventContext *_context;
    _Bool _willDismissAfterOrientationChange;
    GADNCloseButton *_closeButton;
    GADNMRAIDResizeProperties *_resizeProperties;
}

@property(retain, nonatomic) GADNMRAIDResizeProperties *resizeProperties; // @synthesize resizeProperties=_resizeProperties;
@property(readonly, nonatomic) _Bool willDismissAfterOrientationChange; // @synthesize willDismissAfterOrientationChange=_willDismissAfterOrientationChange;
@property(readonly, nonatomic) GADNCloseButton *closeButton; // @synthesize closeButton=_closeButton;
- (void).cxx_destruct;
- (void)handleOrientationChangeEvent;
- (void)didChangeToOrientation:(long long)arg1;
- (void)repositionContentIfNeeded;
- (struct CGRect)contentFrame;
- (void)animateTransparentInterstitialPresentationWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)composeTransparentInterstitialViewsForPresentation;
- (struct CGRect)cropViewFrameForOrientation:(long long)arg1;
- (void)relinquishScreenWithCompletion:(CDUnknownBlockType)arg1;
- (void)presentFromViewController:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)shouldDismissOnApplicationEnteringForeground;
- (_Bool)canPresent;
- (void)addMonitor:(id)arg1;
- (void)closeButtonPressed:(id)arg1;
@property(readonly, nonatomic) GADNEventContext *context;
- (id)init;
- (id)initWithContentView:(id)arg1 resizeProperties:(id)arg2 referenceView:(id)arg3 context:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

