//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADNObserverCollection;

@interface GADNClosePresenterActionMonitor : NSObject
{
    id <GADNPresenting> _presenter;
    GADNObserverCollection *_observers;
}

- (void).cxx_destruct;
- (void)handleCloseNotification;
- (id)initWithPresenter:(id)arg1 messageSource:(id)arg2;

@end

