//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADNEventContextSource.h"
#import "GADNJavascriptEvaluating.h"

@class GADNEventContext, NSString;

@interface GADNJSContext : NSObject <GADNJavascriptEvaluating, GADNEventContextSource>
{
    GADNEventContext *_eventContext;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (void)initialize;
@property(readonly, nonatomic) GADNEventContext *context; // @synthesize context=_eventContext;
- (void).cxx_destruct;
- (void)asyncEvaluateFunction:(id)arg1 parameters:(id)arg2;
- (id)initWithEventContext:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

