//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADNResourceBuffer, GADNVideoConfiguration, NSURL;

@interface GADNVideoAssetLoader : NSObject
{
    NSURL *_sourceURL;
    GADNResourceBuffer *_mainResourceBuffer;
    GADNVideoConfiguration *_videoConfiguration;
    GADNResourceBuffer *_resourceBuffer;
    long long _resourceBufferStartingByteOffset;
}

+ (void)initialize;
- (void).cxx_destruct;
- (void)finishedUsingResourcBuffer:(id)arg1;
- (_Bool)getResourceBuffer:(id *)arg1 startingByteOffset:(long long *)arg2 loadingByteOffset:(long long)arg3 error:(id *)arg4;
- (id)initWithVideoURL:(id)arg1 resourceBuffer:(id)arg2 videoConfiguration:(id)arg3;

@end

