//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADNSignalConfiguration.h"

@interface GADNBannerSignalConfiguration : GADNSignalConfiguration
{
    struct GADNAdSize _adSize;
}

@property(nonatomic) struct GADNAdSize adSize; // @synthesize adSize=_adSize;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithAdUnitID:(id)arg1 adSize:(struct GADNAdSize)arg2;

@end

