//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADNAd, GADNObserverCollection, NSOperationQueue;

@interface GADNRefreshMonitor : NSObject
{
    NSOperationQueue *_observationQueue;
    GADNObserverCollection *_observers;
    GADNAd *_ad;
    _Bool _isEnabled;
    _Bool _isVisible;
    _Bool _isIntermissionOngoing;
}

- (void).cxx_destruct;
- (void)updateRefreshActivity;
- (void)handleIntermissionEvent:(_Bool)arg1;
- (void)handleRefreshAction:(id)arg1;
- (void)handleVisibilityNotification:(id)arg1;
- (id)initWithAd:(id)arg1 messageSource:(id)arg2;

@end

