//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADONativeAd;

@protocol GADNativeAdDelegate <NSObject>

@optional
- (void)nativeAdWillLeaveApplication:(GADONativeAd *)arg1;
- (void)nativeAdDidDismissScreen:(GADONativeAd *)arg1;
- (void)nativeAdWillDismissScreen:(GADONativeAd *)arg1;
- (void)nativeAdWillPresentScreen:(GADONativeAd *)arg1;
- (void)nativeAdDidRecordClick:(GADONativeAd *)arg1;
- (void)nativeAdDidRecordImpression:(GADONativeAd *)arg1;
@end

