//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADNAdRendering.h"

@class GADNAdMediaContent, GADNEventContext, GADNInternalNativeAd, GADNNativeAdAttribution, GADNURLSession, GADNWebViewController, NSArray, NSMutableDictionary, NSObject<OS_dispatch_group>, NSSet, NSString;

@interface GADNInlineSingleNativeAdRenderer : NSObject <GADNAdRendering>
{
    GADNURLSession *_session;
    struct NSDictionary *_adConfiguration;
    GADNEventContext *_adContext;
    NSMutableDictionary *_assets;
    CDUnknownBlockType _renderCompletionHandler;
    _Bool _disableImageLoading;
    NSArray *_images;
    GADNInternalNativeAd *_internalNativeAd;
    GADNAdMediaContent *_mediaContent;
    NSSet *_requiredAssets;
    GADNNativeAdAttribution *_attribution;
    GADNWebViewController *_adVerificationWebViewController;
    NSObject<OS_dispatch_group> *_assetLoadingGroup;
}

- (void).cxx_destruct;
- (void)loadImageArray:(id)arg1 loadedImages:(id)arg2;
- (void)loadSingleImage:(id)arg1 assetName:(id)arg2;
- (void)renderAttribution;
- (void)loadAdVerificationWebView;
- (void)renderMediaContent;
- (void)renderImages;
- (void)renderCustomAssets;
- (void)renderMuteAdInfo;
- (void)renderSingleAssets;
- (void)renderWithServerTransaction:(id)arg1 adConfiguration:(struct NSDictionary *)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (_Bool)isVideo;
- (void)invalidateAndCancel;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

