//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADNObserverCollection, NSObject<OS_dispatch_queue>;

@interface GADNRefreshTimer : NSObject
{
    NSObject<OS_dispatch_queue> *_lockQueue;
    CDUnknownBlockType _refreshHandler;
    long long _expirationIdentifier;
    double _resumeTimestamp;
    double _refreshInterval;
    double _remainingTimeInterval;
    _Bool _isStarted;
    _Bool _isPaused;
    _Bool _isInvalid;
    GADNObserverCollection *_observers;
}

- (void).cxx_destruct;
- (void)forceRefresh;
- (void)expiredWithExpirationIdentifier:(long long)arg1;
- (void)pauseInternal;
- (void)pause;
- (void)resumeInternal;
- (void)resume;
- (void)startInternal;
- (void)start;
- (void)setRefreshHandler:(CDUnknownBlockType)arg1;
- (id)initWithRefreshInterval:(double)arg1 messageSource:(id)arg2;

@end

