//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADNAd, GADNClickProtection, GADNObserverCollection;

@interface GADNOpenDeeplinkMonitor : NSObject
{
    GADNObserverCollection *_observers;
    GADNAd *_ad;
    GADNClickProtection *_clickProtection;
    id <GADNJavascriptEvaluating> _messageSource;
}

- (void).cxx_destruct;
- (void)handleDeeplinkPlusAction:(id)arg1;
- (void)handleOpenDeeplinkAction:(id)arg1;
- (id)initWithAd:(id)arg1 messageSource:(id)arg2 clickProtection:(id)arg3;

@end

