//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADNInternalNativeAd, GADNNativeAdContext, GADNObserverCollection;

@interface GADNNativeAdClickAndImpressionMonitor : NSObject
{
    GADNObserverCollection *_observers;
    GADNInternalNativeAd *_nativeAd;
    GADNNativeAdContext *_nativeAdContext;
}

- (void).cxx_destruct;
- (void)handleConfirmationClick:(double)arg1;
- (void)handleUnconfirmedClickAction:(id)arg1;
- (void)handleAdMutedAction;
- (void)handleImpressionRecordedAction;
- (void)handleClickRecordedAction;
- (void)handleImpression:(id)arg1;
- (void)handleClick:(id)arg1;
- (id)initWithAd:(id)arg1 nativeAdContext:(id)arg2;

@end

