//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADNServerRequest, GADNServerResponse;

@interface GADNServerTransaction : NSObject
{
    GADNServerRequest *_serverRequest;
    GADNServerResponse *_serverResponse;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) GADNServerResponse *serverResponse;
@property(readonly, nonatomic) GADNServerRequest *serverRequest;
- (id)initWithServerRequest:(id)arg1 serverResponse:(id)arg2;

@end

