//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADNObserverCollection, NSOperationQueue;

@interface GADNIntermissionStateMonitor : NSObject
{
    GADNObserverCollection *_observers;
    _Bool _idleTimerWasOriginallyDisabled;
    _Bool _statusBarWasOriginallyHidden;
    NSOperationQueue *_deactivationQueue;
    _Bool _applicationBackgroundedDueToAdAction;
    id <GADNPresenterSource> _presenterSource;
}

@property(nonatomic) __weak id <GADNPresenterSource> presenterSource; // @synthesize presenterSource=_presenterSource;
- (void).cxx_destruct;
- (void)applicationWillEnterForeground;
- (void)setDeactivationQueueSuspended:(_Bool)arg1;
- (void)intermissionWillEnd;
- (void)intermissionDidBegin;
- (id)init;

@end

