//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADNJSCoreConsoleProtocol.h"

@interface GADNJSCoreConsole : NSObject <GADNJSCoreConsoleProtocol>
{
}

- (void)logErrorMessage:(id)arg1;
- (void)logMessage:(id)arg1;

@end

