//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GADNAnimationConfig : NSObject
{
    struct CGRect _initialFrame;
    struct CGRect _finalFrame;
}

+ (id)animationConfigsFromAnimations:(id)arg1;
@property(nonatomic) struct CGRect finalFrame; // @synthesize finalFrame=_finalFrame;
@property(nonatomic) struct CGRect initialFrame; // @synthesize initialFrame=_initialFrame;

@end

