//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADNObserverCollection, GADNScheduler, NSDictionary, NSObject<OS_dispatch_queue>, UIView;

@interface GADNViewVisibilityMonitor : NSObject
{
    GADNObserverCollection *_observers;
    GADNScheduler *_updateVisibilityStatusScheduler;
    UIView *_monitoredView;
    id _messageSource;
    _Bool _viewVisible;
    _Bool _overlayShown;
    NSObject<OS_dispatch_queue> *_lockQueue;
    NSDictionary *_previousViewabilityDictionary;
}

- (void).cxx_destruct;
- (void)updateVisibilityStatus;
- (void)setView:(id)arg1;
- (void)dealloc;
- (void)registerOverlayViewObservers:(id)arg1;
- (id)initWithView:(id)arg1 messageSource:(id)arg2;

@end

