//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADNFullScreenAdViewController, GADNObserverCollection, GADNWebAdView;

@interface GADNOpenGLMonitor : NSObject
{
    GADNWebAdView *_webAdView;
    GADNFullScreenAdViewController *_presenter;
    GADNObserverCollection *_observers;
}

- (void).cxx_destruct;
- (void)applicationDidBecomeActive;
- (void)applicationWillResignActive;
- (id)initWithPresenter:(id)arg1 webAdView:(id)arg2;

@end

