//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADNSignalConfiguration;

@interface GADNSignalGenerator : NSObject
{
    GADNSignalConfiguration *_configuration;
}

- (void).cxx_destruct;
- (void)generateSignalsWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)initWithSignalConfiguration:(id)arg1;

@end

