//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADNObserverCollection;

@interface GADNCanOpenURLsMonitor : NSObject
{
    id <GADNJavascriptEvaluating> _JSContext;
    GADNObserverCollection *_observers;
}

- (void).cxx_destruct;
- (void)handleCanOpenURLsAction:(id)arg1;
- (id)initWithJSContext:(id)arg1;

@end

