//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADNVideoController, UIImage;

@interface GADNMediaContent : NSObject
{
    UIImage *_mainImage;
    id <GADNMediaContentDisplaying> _internalMediaContent;
    GADNVideoController *_videoController;
    _Bool _hasVideoContent;
}

@property(readonly, nonatomic) _Bool hasVideoContent; // @synthesize hasVideoContent=_hasVideoContent;
@property(readonly, nonatomic) GADNVideoController *videoController; // @synthesize videoController=_videoController;
@property(retain, nonatomic) id <GADNMediaContentDisplaying> internalMediaContent; // @synthesize internalMediaContent=_internalMediaContent;
@property(retain, nonatomic) UIImage *mainImage; // @synthesize mainImage=_mainImage;
- (void).cxx_destruct;
@property(readonly, nonatomic) double aspectRatio;

@end

