//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADNAd.h"

@class GADNAdReward, NSString;

@interface GADNInterstitialAd : GADNAd
{
    id <GADNAdPresenting> _adController;
    NSString *_adNetworkClassName;
    GADNAdReward *_reward;
}

@property(retain, nonatomic) GADNAdReward *reward; // @synthesize reward=_reward;
@property(readonly, nonatomic) NSString *adNetworkClassName; // @synthesize adNetworkClassName=_adNetworkClassName;
@property(readonly, nonatomic) id <GADNAdPresenting> adController; // @synthesize adController=_adController;
- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithContext:(id)arg1 adController:(id)arg2 adNetworkClassName:(id)arg3;

@end

