//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADNJSCoreNavigatorProtocol.h"

@class NSString;

@interface GADNJSCoreNavigator : NSObject <GADNJSCoreNavigatorProtocol>
{
    NSString *_userAgent;
}

@property(readonly, nonatomic) NSString *userAgent; // @synthesize userAgent=_userAgent;
- (void).cxx_destruct;
- (id)init;

@end

