//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADNEventContextSource.h"

@class GADNEventContext, GADNWebViewConfiguration, NSString, NSURL, UIView<GADNWebView>;

@interface GADNWebViewController : NSObject <GADNEventContextSource>
{
    GADNEventContext *_context;
    id <GADNWebViewControllerDelegate> _delegate;
    GADNWebViewConfiguration *_configuration;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (void)initialize;
@property(readonly, nonatomic) GADNWebViewConfiguration *configuration; // @synthesize configuration=_configuration;
@property(nonatomic) __weak id <GADNWebViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
@property(readonly, nonatomic) GADNEventContext *context;
- (id)initWithFrame:(struct CGRect)arg1 eventContext:(id)arg2 configuration:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, copy, nonatomic) NSURL *mainDocumentURL; // @dynamic mainDocumentURL;
@property(readonly) Class superclass;
@property(readonly, nonatomic) UIView<GADNWebView> *webView; // @dynamic webView;

@end

