//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADNNativeAd.h"

@class GADNDisplayAdMeasurement, GADNMediaView, GADNObserverCollection, GADNVideoController, NSArray, NSObject<OS_dispatch_queue>, NSString;

@interface GADNNativeCustomTemplateAd : GADNNativeAd
{
    GADNObserverCollection *_observers;
    GADNVideoController *_videoController;
    GADNMediaView *_mediaView;
    GADNDisplayAdMeasurement *_displayAdMeasurement;
    CDUnknownBlockType _customClickHandler;
    CDUnknownBlockType _deprecatedCustomClickHandler;
    NSObject<OS_dispatch_queue> *_lockQueue;
}

- (void).cxx_destruct;
- (void)handleNativeAdCustomClick:(id)arg1;
@property(copy) CDUnknownBlockType customClickHandler;
- (void)recordImpression;
- (void)performClickOnAssetWithKey:(id)arg1 customClickHandler:(CDUnknownBlockType)arg2;
- (void)performClickOnAssetWithKey:(id)arg1;
@property(readonly, nonatomic) NSArray *availableAssetKeys;
- (void)setDisplayAdMeasurement:(id)arg1;
- (id)displayAdMeasurement;
@property(readonly, nonatomic) GADNVideoController *videoController;
@property(readonly, nonatomic) GADNMediaView *mediaView;
- (id)adType;
@property(readonly, nonatomic) NSString *templateID;
- (id)stringForKey:(id)arg1;
- (id)imageForKey:(id)arg1;
- (id)description;
- (id)initWithInternalNativeAd:(id)arg1;

@end

