//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADNJSCoreInterfaceProtocol.h"

@class GADNJSCoreJSContext;

@interface GADNJSCoreInterface : NSObject <GADNJSCoreInterfaceProtocol>
{
    GADNJSCoreJSContext *_JSCoreJSContext;
}

- (void).cxx_destruct;
- (void)notifyWithURLString:(id)arg1;
- (id)init;
- (id)initWithJSCoreJSContext:(id)arg1;

@end

