//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SKStoreProductViewControllerDelegate.h"

@class GADOStoreKitProduct, NSString, SKStoreProductViewController;

@interface GADOStoreKitProductOpener : NSObject <SKStoreProductViewControllerDelegate>
{
    GADOStoreKitProduct *_storeKitProduct;
    SKStoreProductViewController *_weakController;
    _Bool _isPresenting;
    _Bool _isPresented;
    _Bool _shouldDismissAfterPresentation;
    _Bool _dismissed;
}

- (void).cxx_destruct;
- (void)productViewControllerDidFinish:(id)arg1;
- (void)dismiss;
- (void)openWithRootViewController:(id)arg1 slot:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
@property(readonly) _Bool dismissed;
- (id)initWithStoreKitProduct:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

