//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADOGMSGHandler.h"

@class GADOStoreKitProductInlineRenderer;

@interface GADOAnimateViewGMSGHandler : GADOGMSGHandler
{
    GADOStoreKitProductInlineRenderer *_inlineStorKitProductRenderer;
}

+ (id)actionBlockDictionary;
- (void).cxx_destruct;
- (void)renderStoreKitProductInlineWithAdView:(id)arg1 animationData:(id)arg2;
- (void)performAdView:(id)arg1 animations:(id)arg2;
- (void)prepareAdView:(id)arg1 animations:(id)arg2;
- (void)adView:(id)arg1 didReceiveAnimateViewNotification:(id)arg2;

@end

