//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADOAdView.h"

@interface GADOBrowserAdView : GADOAdView
{
}

- (id)browserViewController;
- (void)setViewController:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

