//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADOAdLoaderOptions.h"

@interface GADONativeAdViewAdOptions : GADOAdLoaderOptions
{
    long long _preferredAdChoicesPosition;
}

@property(nonatomic) long long preferredAdChoicesPosition; // @synthesize preferredAdChoicesPosition=_preferredAdChoicesPosition;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

