//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADOSlot, NSDictionary;

@protocol GADOSlotAdKeyDelegate <NSObject>
- (NSDictionary *)viewHierarchyInformationForSlot:(GADOSlot *)arg1;
- (void)cacheViewHierarchyInformationForSlot:(GADOSlot *)arg1;
@end

