//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADOAdReward, GADOInterstitial, NSString;

@protocol GADOInterstitialRewardBasedVideoAdDelegate <NSObject>
- (void)interstitial:(GADOInterstitial *)arg1 didChangeAdMetadata:(NSString *)arg2 withInfo:(NSString *)arg3;
- (void)interstitial:(GADOInterstitial *)arg1 didRewardUserWithReward:(GADOAdReward *)arg2;
- (void)interstitialDidCompletePlayingRewardBasedVideoAd:(GADOInterstitial *)arg1;
- (void)interstitialDidStartPlayingRewardBasedVideoAd:(GADOInterstitial *)arg1;
@end

