//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADOWebView;

@interface GADOMWebViewRenderedChecker : NSObject
{
    GADOWebView *_webView;
    id <GADOMWebViewRenderedCheckerDelegate> _delegate;
}

@property(nonatomic) __weak id <GADOMWebViewRenderedCheckerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak GADOWebView *webView; // @synthesize webView=_webView;
- (void).cxx_destruct;
- (double)percentOfImage:(id)arg1 ofColor:(id)arg2;
- (void)checkIsContentRenderedInWebView;
- (id)init;
- (id)initWithWebView:(id)arg1 delegate:(id)arg2;

@end

