//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADOViewMonitorDelegate.h"

@class GADOViewMonitor, NSString, UIView;

@interface GADOImpressionMonitor : NSObject <GADOViewMonitorDelegate>
{
    long long _impressionDefinition;
    UIView *_monitoredView;
    GADOViewMonitor *_viewMonitor;
    id <GADOImpressionMonitorDelegate> _delegate;
}

@property(nonatomic) __weak id <GADOImpressionMonitorDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)viewMonitorDidRefresh:(id)arg1;
- (void)startImpressionDefinitionVisible;
- (void)startImpressionDefinitionAdLoaded;
- (void)startMonitoring;
- (void)stopMonitoring;
- (void)didMonitorImpression;
- (id)init;
- (id)initWithView:(id)arg1 impressionDefinition:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

