//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADMAdNetworkConnector, GADOAd, GADOAdLoaderConfiguration, GADOMAdNetworkConfig, GADOMConfig, GADOMediatedAd;

@protocol GADOAdMediationDelegate <NSObject>
- (GADMAdNetworkConnector *)mediationConnectorForConfiguration:(GADOMConfig *)arg1 networkConfiguration:(GADOMAdNetworkConfig *)arg2;

@optional
- (void)ad:(GADOAd *)arg1 processMediatedAd:(GADOMediatedAd *)arg2 withCompletionHandler:(void (^)(NSError *))arg3;
- (GADOAdLoaderConfiguration *)adLoaderConfigurationForAd:(GADOAd *)arg1 networkConfiguration:(GADOMAdNetworkConfig *)arg2;
@end

