//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface GADOConfiguration : NSObject <NSCoding, NSCopying>
{
    NSMutableDictionary *_parameters;
    NSMutableDictionary *_priorities;
    NSObject<OS_dispatch_queue> *_lockQueue;
    id <GADOConfigurationDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)addEntriesFromDictionary:(id)arg1 priorities:(id)arg2;
- (void)addEntriesFromDictionary:(id)arg1 priority:(long long)arg2;
- (void)setObject:(id)arg1 forKey:(id)arg2 priority:(long long)arg3;
- (void)didUpdate;
- (_Bool)updatedBySettingValue:(id)arg1 withPriority:(long long)arg2 forKey:(id)arg3;
- (id)objectForKeyedSubscript:(id)arg1;
@property __weak id <GADOConfigurationDelegate> delegate;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

