//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVAssetResourceLoaderDelegate.h"

@class AVPlayerItem, AVURLAsset, GADOAssetLoadingVideoPlayerItem, GADOGCacheURLLoader, GADOResourceCache, GADOVideoConfiguration, GADOVideoPlayer, NSMutableArray, NSString, NSURL;

@interface GADOVideoLoader : NSObject <AVAssetResourceLoaderDelegate>
{
    NSURL *_sourceURL;
    GADOGCacheURLLoader *_gcacheURLLoader;
    _Bool _hasNotifiedVideoLoadingStarted;
    _Bool _hasNotifiedVideoLoadingFailed;
    NSMutableArray *_pendingRequests;
    AVURLAsset *_cachedResourceAsset;
    _Bool _isObservingResourceCache;
    GADOResourceCache *_resourceCache;
    GADOVideoPlayer *_player;
    GADOVideoConfiguration *_configuration;
    GADOAssetLoadingVideoPlayerItem *_assetLoadingPlayerItem;
    _Bool _hasBeenUsed;
    AVPlayerItem *_playerItem;
    id <GADOVideoLoaderDelegate> _delegate;
}

@property(readonly, nonatomic) _Bool hasBeenUsed; // @synthesize hasBeenUsed=_hasBeenUsed;
@property(nonatomic) __weak id <GADOVideoLoaderDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) AVPlayerItem *playerItem; // @synthesize playerItem=_playerItem;
- (void).cxx_destruct;
- (void)resourceCacheDidUpdateCacheNotification:(id)arg1;
- (void)stopObservingResourceCacheUpdates;
- (void)observeResourceCacheUpdates;
- (void)resourceLoader:(id)arg1 didCancelLoadingRequest:(id)arg2;
- (_Bool)processAssetResourceLoadingRequest:(id)arg1 withError:(id *)arg2;
- (_Bool)resourceLoader:(id)arg1 shouldWaitForLoadingOfRequestedResource:(id)arg2;
- (void)notifyVideoLoaderFailedToLoadURL:(id)arg1 withError:(id)arg2;
- (void)notifyVideoLoaderDidStartLoadingURL:(id)arg1;
- (void)loadWithResourceCache:(id)arg1;
- (void)loadAdvanceControlVideoURL:(id)arg1 resourceCache:(id)arg2;
- (void)loadGCacheURL:(id)arg1;
- (void)loadStandardURL:(id)arg1;
- (void)cancel;
- (void)dealloc;
- (void)loadURL:(id)arg1 resourceCache:(id)arg2 configuration:(id)arg3;
- (id)initWithPlayer:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

