//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class GADOSDKCoreGMSGHandler, NSDictionary, NSString;

@protocol GADOSDKCoreGMSGHandlerDelegate
- (void)SDKCoreGMSGHandlerDidReceiveResumeSDKCoreRefreshAction:(GADOSDKCoreGMSGHandler *)arg1;
- (void)SDKCoreGMSGHandlerDidReceivePauseSDKCoreRefreshAction:(GADOSDKCoreGMSGHandler *)arg1;
- (void)SDKCoreGMSGHandler:(GADOSDKCoreGMSGHandler *)arg1 didReceiveResultActionWithRequestID:(NSString *)arg2 arguments:(NSDictionary *)arg3;
- (void)SDKCoreGMSGHandlerDidReceiveSDKCoreUpdateNotification:(GADOSDKCoreGMSGHandler *)arg1;
- (void)SDKCoreGMSGHandler:(GADOSDKCoreGMSGHandler *)arg1 didLoadSDKConstants:(NSDictionary *)arg2;
- (void)SDKCoreGMSGHandler:(GADOSDKCoreGMSGHandler *)arg1 didReceiveInvalidAdWithRequestID:(NSString *)arg2 parameters:(NSDictionary *)arg3;
- (void)SDKCoreGMSGHandler:(GADOSDKCoreGMSGHandler *)arg1 loadAdWithRequestID:(NSString *)arg2 parameters:(NSDictionary *)arg3;
- (void)SDKCoreGMSGHandler:(GADOSDKCoreGMSGHandler *)arg1 loadAdURLWithRequestID:(NSString *)arg2 parameters:(NSDictionary *)arg3;
@end

