//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CTTelephonyNetworkInfo, NSObject<OS_dispatch_queue>, NSString;

@interface GADONetwork : NSObject
{
    unsigned long long _networkType;
    unsigned long long _lastKnownNetworkType;
    NSObject<OS_dispatch_queue> *_lockQueue;
    NSObject<OS_dispatch_queue> *_enableCheckingQueue;
    struct __SCNetworkReachability *_networkReachabilityRef;
    id <NSObject> _radioAccessTechnologyChangeObserver;
    CTTelephonyNetworkInfo *_telephonyNetworkInfo;
    NSString *_radioAccessTechnology;
    NSString *_lastKnownRadioAccessTechnology;
    NSString *_userAgentString;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(copy) NSString *userAgentString;
- (void)setRadioAccessTechnology:(id)arg1;
- (void)setNetworkTypeFromFlags:(unsigned int)arg1;
- (void)setNetworkType:(unsigned long long)arg1;
- (id)requestDictionary;
- (void)enableRadioAccessTechnologyChecking;
- (void)dealloc;
- (id)init;

@end

