//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIGestureRecognizerDelegate.h"

@class GADONativeAd, NSObject<OS_dispatch_queue>, NSString, UITapGestureRecognizer, UIView;

@interface GADONativeClickConfirmingViewMonitor : NSObject <UIGestureRecognizerDelegate>
{
    GADONativeAd *_nativeAd;
    UITapGestureRecognizer *_singleTap;
    id _clickConfirmingViewObserver;
    NSObject<OS_dispatch_queue> *_lockQueue;
    UIView *_clickConfirmingView;
}

- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)setClickConfirmingView:(id)arg1;
@property(readonly, nonatomic) __weak UIView *clickConfirmingView;
- (void)handleTap:(id)arg1;
- (void)handleAssociatedNativeAd:(id)arg1;
- (void)untrackClickConfirmingView;
- (void)trackClickConfirmingView:(id)arg1;
- (id)initWithNativeAd:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

