//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADOIntermission, UIViewController;

@protocol GADOIntermitting <NSObject>
@property(readonly, nonatomic) GADOIntermission *intermission;
- (void)relinquishScreenWithCompletion:(void (^)(void))arg1;
- (_Bool)shouldDismissOnApplicationEnteringForeground;
- (void)presentFromViewController:(UIViewController *)arg1 completion:(void (^)(void))arg2;

@optional
- (void)didReturnToApplication;
@end

