//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSMutableSet, NSObject<OS_dispatch_queue>;

@interface GADORTBAdapterManager : NSObject
{
    NSObject<OS_dispatch_queue> *_lockQueue;
    NSMutableSet *_registeredClassNames;
    NSMutableSet *_setUpRTBClassNames;
    NSMutableDictionary *_adUnitToAdapterNames;
    NSMutableDictionary *_adapterNameToAdapterConfiguration;
    NSMutableDictionary *_mediationCredentials;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)credentialsForAdapterClass:(Class)arg1 adUnitID:(id)arg2;
- (id)registeredAdapterNamesForAdUnitID:(id)arg1;
- (void)registerMediationAdapterClassName:(id)arg1;
- (void)registerMediationAdapterClassName:(id)arg1 configuration:(id)arg2;
- (void)updateAdapter:(Class)arg1 configuration:(id)arg2;
- (void)updateAdUnitAdapterConfiguration:(id)arg1;
- (void)updateRTBAdapters;
- (void)dealloc;
- (id)init;

@end

