//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADOScheduler, UIView;

@interface GADOViewBoundsMonitor : NSObject
{
    UIView *_monitoredView;
    id <GADOViewBoundsMonitorDelegate> _delegate;
    GADOScheduler *_updateViewBoundsScheduler;
    struct CGRect _monitoredViewBounds;
}

- (void).cxx_destruct;
- (void)updateViewBounds;
- (void)stopMonitoring;
- (void)startMonitoringWithSamplingInterval:(double)arg1;
- (id)init;
- (id)initWithView:(id)arg1 delegate:(id)arg2;

@end

