//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADOMediationAdConfiguration.h"

@interface GADOMediationBannerAdConfiguration : GADOMediationAdConfiguration
{
    struct GADOAdSize _adSize;
}

@property(readonly, nonatomic) struct GADOAdSize adSize; // @synthesize adSize=_adSize;
- (id)initWithConnector:(id)arg1 credentials:(id)arg2;
- (id)init;
- (id)initWithAdSize:(struct GADOAdSize)arg1 connector:(id)arg2 credentials:(id)arg3;

@end

