//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSSet, NSString;

@interface GADOMRAIDInterceptor : NSObject
{
    NSObject<OS_dispatch_queue> *_lockQueue;
    NSString *_bannerImplementationURLString;
    NSString *_expandedBannerImplementationURLString;
    NSString *_interstitialImplementationURLString;
    NSSet *_implementationURLStrings;
    _Bool _enabled;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(copy) NSString *interstitialImplementationURLString;
@property(copy) NSString *expandedBannerImplementationURLString;
@property(copy) NSString *bannerImplementationURLString;
- (_Bool)shouldRedirectURL:(id)arg1;
- (_Bool)canRedirect;
- (void)updateImplementationURLStrings;
- (_Bool)URLisImplementationURL:(id)arg1;
- (void)setEnabled:(_Bool)arg1;
- (id)init;
- (id)MRAIDURLStringForAdView:(id)arg1;

@end

