//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADOAdAppViewController.h"

@class UIImageView;

@interface GADOExpandedAdAppViewController : GADOAdAppViewController
{
    UIImageView *_renderedBanner;
}

- (void).cxx_destruct;
- (void)relinquishScreenWithCompletion:(CDUnknownBlockType)arg1;
- (void)configureView;
- (_Bool)isLoaded;
- (void)dealloc;
- (id)initWithAdView:(id)arg1;

@end

