//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADOInterstitial;

@protocol GADOInterstitialAdClickDelegate <NSObject>

@optional
- (void)interstitialDidReceiveAdClick:(GADOInterstitial *)arg1;
@end

