//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADORequest, NSMutableArray, NSObject<OS_dispatch_queue>, NSString;

@interface GADOInterstitialPool : NSObject
{
    NSMutableArray *_entries;
    GADORequest *_request;
    id <GADOInterstitialPoolDelegate> _delegate;
    NSObject<OS_dispatch_queue> *_lockQueue;
    NSString *_adUnitID;
}

@property(readonly, copy, nonatomic) NSString *adUnitID; // @synthesize adUnitID=_adUnitID;
- (void).cxx_destruct;
- (id)nextEntry;
- (void)fill;
- (void)addCacheEntryWithTimeout:(double)arg1 maxCount:(long long)arg2;
- (void)scheduleTimeout:(double)arg1 cacheEntry:(id)arg2;
- (void)removeObject:(id)arg1;
@property __weak id <GADOInterstitialPoolDelegate> delegate;
@property(copy) GADORequest *request;
- (id)initWithRequest:(id)arg1 adUnitID:(id)arg2;
- (id)init;

@end

