//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADRewardBasedVideoAdDelegate.h"

@class GADORewardBasedVideoAd, NSError;

@protocol GADORewardedAdInternalDelegate <GADRewardBasedVideoAdDelegate>
- (void)rewardBasedVideoAd:(GADORewardBasedVideoAd *)arg1 didFailToPresentRewardedAdWithError:(NSError *)arg2;
@end

