//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADOAdType, GADOMConfig, UIViewController;

@protocol GADOMSlotDelegate <NSObject>
- (void)presentInterstitialFromRootViewController:(UIViewController *)arg1;
- (_Bool)changeAdTypeTo:(GADOAdType *)arg1;
- (void)mediateForAdType:(GADOAdType *)arg1 config:(GADOMConfig *)arg2;
@end

