//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADOWebKitWebView, NSString;

@protocol GADOWebKitWebViewMRAIDDelegate <NSObject>
- (NSString *)MRAIDJavaScriptURLStringForWebView:(GADOWebKitWebView *)arg1;
@end

