//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADOMediaContentDisplaying.h"

@class GADOMediationNativeAdVideoController, GADONativeAdImage, NSString, UIImageView, UIView;

@interface GADOMediationNativeAdMediaContent : NSObject <GADOMediaContentDisplaying>
{
    id _mediatedNativeAd;
    UIView *_mediaView;
    GADONativeAdImage *_mainImage;
    // Error parsing type: Ad, name: _mainImageAspectRatio
    UIImageView *_mainImageView;
    GADOMediationNativeAdVideoController *_videoController;
}

@property(readonly, nonatomic) GADOMediationNativeAdVideoController *videoController; // @synthesize videoController=_videoController;
- (void).cxx_destruct;
- (double)aspectRatio;
- (void)loadVideoWithCompletionHandler:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) UIView *mediaView;
- (void)setMainImage:(id)arg1;
- (id)initWithMediatedUnifiedNativeAd:(id)arg1;
- (id)initWithMediatedNativeContentAd:(id)arg1;
- (id)initWithMediatedNativeAppInstallAd:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

