//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADOGMSGHandler.h"

@interface GADORewardBasedVideoAdGMSGHandler : GADOGMSGHandler
{
}

+ (id)actionBlockDictionary;
- (void)adView:(id)arg1 didReceiveVideoCompleteAction:(id)arg2;
- (void)adView:(id)arg1 didReceiveGrantRewardAction:(id)arg2;
- (void)adView:(id)arg1 didReceiveStartVideoAction:(id)arg2;
- (void)adView:(id)arg1 didReceiveRewardBasedVideoAdAction:(id)arg2;

@end

