//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIImage;

@interface GADOMediaContent : NSObject
{
    UIImage *_mainImage;
    id <GADOMediaContentDisplaying> _internalMediaContent;
}

@property(retain, nonatomic) id <GADOMediaContentDisplaying> internalMediaContent; // @synthesize internalMediaContent=_internalMediaContent;
@property(retain, nonatomic) UIImage *mainImage; // @synthesize mainImage=_mainImage;
- (void).cxx_destruct;
@property(readonly, nonatomic) double aspectRatio;

@end

