//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITapGestureRecognizer.h"

@class GADONativeAdViewPolicy;

@interface GADONativeAdTapGestureRecognizer : UITapGestureRecognizer
{
    GADONativeAdViewPolicy *_nativeAdViewPolicy;
}

@property(retain, nonatomic) GADONativeAdViewPolicy *nativeAdViewPolicy; // @synthesize nativeAdViewPolicy=_nativeAdViewPolicy;
- (void).cxx_destruct;

@end

