//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADORewardedAdInternalDelegate.h"
#import "GADRewardBasedVideoAdDelegate.h"

@class GADOAdReward, GADORewardBasedVideoAd, GADOServerSideVerificationOptions, NSString;

@interface GADORewardedAd : NSObject <GADRewardBasedVideoAdDelegate, GADORewardedAdInternalDelegate>
{
    GADORewardBasedVideoAd *_rewardBasedVideoAd;
    CDUnknownBlockType _completionHandler;
    id <GADRewardedAdDelegate> _delegate;
    id <GADRewardedAdMetadataDelegate> _adMetadataDelegate;
    NSString *_adUnitID;
    GADOServerSideVerificationOptions *_serverSideVerificationOptions;
}

@property(copy, nonatomic) GADOServerSideVerificationOptions *serverSideVerificationOptions; // @synthesize serverSideVerificationOptions=_serverSideVerificationOptions;
@property(readonly, copy, nonatomic) NSString *adUnitID; // @synthesize adUnitID=_adUnitID;
- (void).cxx_destruct;
- (void)rewardBasedVideoAdMetadataDidChange:(id)arg1;
- (void)rewardBasedVideoAd:(id)arg1 didFailToPresentRewardedAdWithError:(id)arg2;
- (void)rewardBasedVideoAdDidClose:(id)arg1;
- (void)rewardBasedVideoAd:(id)arg1 didRewardUserWithReward:(id)arg2;
- (void)rewardBasedVideoAdDidOpen:(id)arg1;
- (void)rewardBasedVideoAd:(id)arg1 didFailToLoadWithError:(id)arg2;
- (void)rewardBasedVideoAdDidReceiveAd:(id)arg1;
@property(readonly, copy, nonatomic) NSString *adNetworkClassName;
@property(readonly, nonatomic) GADOAdReward *reward;
- (void)setAdMetadataDelegate:(id)arg1;
- (id)adMetadataDelegate;
- (id)adMetadata;
- (void)setAdMetadata:(id)arg1;
@property(readonly, nonatomic, getter=isReady) _Bool ready;
- (void)presentFromRootViewController:(id)arg1 delegate:(id)arg2;
- (void)loadRequest:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)initWithAdUnitID:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

