//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADOInterstitial;

@interface GADOInterstitialOwner : NSObject
{
    _Bool _isSlotCreated;
    _Bool _isInterstitialCloseDelayed;
    _Bool _isDismissed;
    GADOInterstitial *_weakInterstitial;
    GADOInterstitial *_presentedInterstitial;
    GADOInterstitial *_pageCloseDelayedInterstitial;
    double _delayPageCloseTimeoutInterval;
}

- (void).cxx_destruct;
- (void)interstitialDelayPageCloseStopped;
- (void)interstitialDelayPageCloseStarted;
- (void)stopObserving;
- (void)observeInterstitial:(id)arg1;
- (void)moveAdViewToPlaceholderWindow:(id)arg1;
- (void)interstitialIsDismissed;
- (void)interstitialWillBePresented;
- (void)interstitialDidCreateSlot;
- (void)dealloc;
- (id)initWithInterstitial:(id)arg1;

@end

