//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADOScheduler, GADOWebViewPinger, NSMutableArray, NSMutableSet, NSObject<OS_dispatch_queue>;

@interface GADOPinger : NSObject
{
    NSObject<OS_dispatch_queue> *_lockQueue;
    GADOScheduler *_scheduler;
    long long _maximumRetryURLCount;
    long long _URLRetryCount;
    NSMutableArray *_retryGroupKeys;
    NSMutableSet *_pingedURLs;
    GADOWebViewPinger *_webViewPinger;
    _Bool _reloadRequired;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)removeRetryURLString:(id)arg1 retryGroupKey:(id)arg2;
- (void)storeRetryURLString:(id)arg1 retryGroupKey:(id)arg2;
- (void)start;
- (void)pingWithRetryGroupKey:(id)arg1 URL:(id)arg2 retryURLString:(id)arg3;
- (void)pingRetryURLs;
- (void)sendPing:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)pingURLString:(id)arg1 queue:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)init;

@end

