//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADOAdReward, GADORewardBasedVideoAdGMSGHandler;

@protocol GADORewardBasedVideoAdGMSGHandlerDelegate <NSObject>

@optional
- (void)rewardBasedVideoAdGMSGHandlerDidReceiveVideoCompleteNotification:(GADORewardBasedVideoAdGMSGHandler *)arg1;
- (void)rewardBasedVideoAdGMSGHandler:(GADORewardBasedVideoAdGMSGHandler *)arg1 didReceiveRewardNotificationWithRewardItem:(GADOAdReward *)arg2;
- (void)rewardBasedVideoAdGMSGHandlerDidReceiveStartVideoNotification:(GADORewardBasedVideoAdGMSGHandler *)arg1;
@end

