//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADOSlot, NSDictionary;

@protocol GADOSlotAdEventDelegate <NSObject>

@optional
- (void)slotDidMuteAd:(GADOSlot *)arg1;
- (void)slot:(GADOSlot *)arg1 didReceiveUnconfirmedClickWithClickInfo:(NSDictionary *)arg2;
- (void)slotDidRecordClick:(GADOSlot *)arg1;
- (void)slotDidRecordImpression:(GADOSlot *)arg1;
- (void)slot:(GADOSlot *)arg1 didLoadVideoWithSize:(struct CGSize)arg2;
- (void)slotWillLeaveApplication:(GADOSlot *)arg1;
- (void)slotDidDismissScreen:(GADOSlot *)arg1;
- (void)slotWillDismissScreen:(GADOSlot *)arg1;
- (void)slotWillPresentScreen:(GADOSlot *)arg1;
@end

