//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADONativeAd.h"

#import "GADOLoadable.h"
#import "GADOMediatedNativeCustomTemplateAd.h"

@class GADOAdMediaContent, GADOMediaView, GADOVideoController, NSArray, NSDictionary, NSMutableDictionary, NSMutableSet, NSObject<OS_dispatch_queue>, NSString;

@interface GADONativeCustomTemplateAd : GADONativeAd <GADOMediatedNativeCustomTemplateAd, GADOLoadable>
{
    _Bool _disableImageLoading;
    NSObject<OS_dispatch_queue> *_lockQueue;
    NSDictionary *_optionalImages;
    NSDictionary *_requiredImages;
    NSMutableDictionary *_imageAssets;
    NSDictionary *_stringAssets;
    GADOAdMediaContent *_mediaContent;
    GADOMediaView *_mediaView;
    NSMutableSet *_availableAssetKeys;
    GADOVideoController *_videoController;
    CDUnknownBlockType _customClickHandler;
    CDUnknownBlockType _deprecatedCustomClickHandler;
    NSString *_templateID;
}

+ (_Bool)canInitWithAdLoader:(id)arg1 error:(id *)arg2;
+ (id)requestParametersForAdLoader:(id)arg1;
+ (id)requiredDelegateProtocol;
+ (_Bool)canConvertToInstreamAd;
+ (id)loadableAdWithAdDictionary:(id)arg1 options:(id)arg2;
@property(readonly, nonatomic) GADOVideoController *videoController; // @synthesize videoController=_videoController;
@property(readonly, nonatomic) NSString *templateID; // @synthesize templateID=_templateID;
- (void).cxx_destruct;
- (void)adLoaderDidReceiveAd:(id)arg1;
- (void)loadAssetsWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)loadImageAssetsWithImageDictionary:(id)arg1;
- (void)setImage:(id)arg1 forKey:(id)arg2;
- (void)beginObservingVideoClickNotifications;
- (void)handleVideoClickNotifications;
- (void)handleNativeAdCustomClick:(id)arg1;
@property(readonly, nonatomic) GADOMediaView *mediaView;
- (id)stringForKey:(id)arg1;
- (id)imageForKey:(id)arg1;
@property(readonly, nonatomic) NSArray *availableAssetKeys;
- (id)requiredAssets;
@property(copy) CDUnknownBlockType customClickHandler;
- (void)recordImpression;
- (void)performClickOnAssetWithKey:(id)arg1 customClickHandler:(CDUnknownBlockType)arg2;
- (void)performClickOnAssetWithKey:(id)arg1;
- (id)adFormatTemplateID;
- (_Bool)hasValidConfigurationForRequestParameters:(id)arg1;
- (void)setSlot:(id)arg1;
- (void)removeCustomClickObserver;
@property(readonly, copy) NSString *description;
- (void)dealloc;
- (id)initWithMediatedNativeAd:(id)arg1 options:(id)arg2;
- (id)initWithDictionary:(id)arg1 options:(id)arg2;
- (void)GADONativeCustomTemplateAd_category;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

