//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GADOPublicKey : NSObject
{
    struct __SecCertificate *_certificate;
    struct __SecTrust *_trustStore;
    struct __SecKey *_key;
}

- (_Bool)isSignatureValid:(id)arg1 forMessage:(id)arg2;
- (void)dealloc;
- (id)initWithCertificateData:(id)arg1;

@end

