//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface GADOStatisticsCore : NSObject
{
    NSMutableDictionary *_statistics;
    NSString *_userDefaultsKey;
    NSObject<OS_dispatch_queue> *_lockQueue;
    NSObject<OS_dispatch_queue> *_writeQueue;
}

- (void).cxx_destruct;
- (void)removeObjectForKey:(id)arg1;
- (void)appendDictionary:(id)arg1 toArrayForKey:(id)arg2;
- (void)appendString:(id)arg1 toArrayForKey:(id)arg2;
- (id)arrayForKey:(id)arg1;
- (void)setIdentifier:(id)arg1;
- (void)savePersistentStatistics;
- (void)applicationWillTerminate:(id)arg1;
@property(readonly, copy, nonatomic) NSDictionary *statistics;
- (void)dealloc;
- (id)init;

@end

