//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADMAdNetworkAdapter.h"
#import "GADMediationNativeAdEventDelegate.h"

@class GADMAdNetworkConnector, NSString;

@interface GADOMRTBNativeAdapter : NSObject <GADMediationNativeAdEventDelegate, GADMAdNetworkAdapter>
{
    GADMAdNetworkConnector *_connector;
    id <GADMediationNativeAd> _mediatedAd;
    _Bool _handlesUserClicks;
    _Bool _handlesUserImpressions;
}

+ (Class)networkExtrasClass;
+ (id)adapterVersion;
- (void).cxx_destruct;
- (void)getBannerWithSize:(struct GADOAdSize)arg1;
- (void)presentInterstitialFromRootViewController:(id)arg1;
- (void)stopBeingDelegate;
- (void)getInterstitial;
- (void)didUnmuteVideo;
- (void)didMuteVideo;
- (void)didEndVideo;
- (void)didPauseVideo;
- (void)didPlayVideo;
- (void)didFailToPresentWithError:(id)arg1;
- (void)willBackgroundApplication;
- (void)didDismissFullScreenView;
- (void)willDismissFullScreenView;
- (void)willPresentFullScreenView;
- (void)reportClick;
- (void)reportImpression;
- (_Bool)adapter:(id)arg1 completedLoadForConnector:(id)arg2 withMediatedAd:(id)arg3 error:(id)arg4;
- (_Bool)handlesUserImpressions;
- (_Bool)handlesUserClicks;
- (void)getNativeAdWithAdTypes:(id)arg1 options:(id)arg2;
- (id)initWithGADMAdNetworkConnector:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

