//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADOSlot, NSHashTable, NSOperationQueue;

@interface GADOIntermission : NSObject
{
    _Bool _publisherIdleTimerDisabled;
    GADOSlot *_slot;
    _Bool _statusBarWasOriginallyHidden;
    long long _activeParticipantsCount;
    long long _deactivatingParticipantsCount;
    NSHashTable *_activeParticipants;
    NSHashTable *_deactivatingParticipants;
    NSOperationQueue *_deactivationQueue;
    _Bool _statusBarOverridden;
}

- (void).cxx_destruct;
- (void)applicationWillEnterForegroundWithNotification:(id)arg1;
- (void)participantDidRelinquishScreen:(id)arg1;
- (void)participantWillRelinquishScreen:(id)arg1;
- (void)participantWillOverrideStatusBarVisibility:(id)arg1;
- (void)addParticipant:(id)arg1;
- (void)didEnd;
- (void)willEnd;
- (void)begin;
- (void)cleanUpDeallocatedParticipants;
- (id)activeParticipants;
- (void)dealloc;
- (id)initWithSlot:(id)arg1;
- (id)init;

@end

