//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADOScheduler, NSObject<OS_dispatch_queue>, UIView;

@interface GADOViewMonitor : NSObject
{
    GADOScheduler *_updateViewBoundsScheduler;
    NSObject<OS_dispatch_queue> *_lockQueue;
    id <GADOViewMonitorDelegate> _delegate;
    struct CGRect _monitoredViewVisibleBounds;
    _Bool _monitoredViewVisible;
    UIView *_monitoredView;
    _Bool _shouldUseZOrderViewVisibility;
}

- (void).cxx_destruct;
@property(readonly) _Bool monitoredViewVisible;
@property(readonly) struct CGRect monitoredViewVisibleBounds;
- (void)setMonitoredViewVisibleBounds:(struct CGRect)arg1;
@property __weak id <GADOViewMonitorDelegate> delegate;
- (void)updateViewBounds;
- (void)stopMonitoring;
- (void)sample;
- (void)startMonitoringWithSamplingInterval:(double)arg1;
- (id)init;
- (id)initWithView:(id)arg1 shouldUseZOrderViewVisibility:(_Bool)arg2;
- (id)initWithView:(id)arg1;

@end

