//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADODelayPageLoadGMSGHandler;

@protocol GADODelayLoadDelegate <NSObject>
- (void)loadHandlerDidChangeDelay:(GADODelayPageLoadGMSGHandler *)arg1 from:(long long)arg2 to:(long long)arg3;
- (void)loadHandlerDidCancel:(GADODelayPageLoadGMSGHandler *)arg1;
@end

