//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GADOClickTracker : NSObject
{
    unsigned long long _backgroundTaskID;
    _Bool _hasTracked;
    id <GADOClickTrackerDelegate> _delegate;
}

@property(readonly, nonatomic) _Bool hasTracked; // @synthesize hasTracked=_hasTracked;
@property(nonatomic) __weak id <GADOClickTrackerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)endBackgroundTask;
- (void)beginBackgroundTask;
- (void)URLTrackingDidEnd:(id)arg1 success:(_Bool)arg2;
- (void)trackURL:(id)arg1;
- (void)reset;
- (void)dealloc;
- (id)init;

@end

