//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>;

@interface GADONetworkLogger : NSObject
{
    NSObject<OS_dispatch_queue> *_logQueue;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)logNetworkError:(id)arg1 components:(id)arg2;
- (void)logResponseBody:(id)arg1 withContent:(_Bool)arg2 components:(id)arg3;
- (void)logResponseHeader:(id)arg1 components:(id)arg2;
- (void)logRequest:(id)arg1 components:(id)arg2 requestOnly:(_Bool)arg3;
- (void)logEvent:(id)arg1 timestamp:(id)arg2 components:(id)arg3 userInfo:(id)arg4;
- (void)logMessage:(id)arg1;
@property(readonly, getter=isEnabled) _Bool enabled;
- (id)init;

@end

