//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADOAdViewVideoController, NSMutableArray;

@interface GADOInstreamAdVideoController : NSObject
{
    GADOAdViewVideoController *_videoController;
    CDUnknownBlockType _playbackEndedBlock;
    NSMutableArray *_observers;
    _Bool _isMuted;
    id <GADOInstreamAdVideoControllerDelegate> _delegate;
    double _duration;
    double _currentTime;
}

@property(nonatomic) double currentTime; // @synthesize currentTime=_currentTime;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(nonatomic) __weak id <GADOInstreamAdVideoControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)startObservingAdViewVideoController;
- (void)stopObservingAdViewVideoController;
@property(nonatomic, getter=isMuted) _Bool muted;
- (void)pause;
- (void)play;
- (void)setAdViewVideoController:(id)arg1;
- (void)setVideoPlaybackEndedBlock:(CDUnknownBlockType)arg1;
- (void)dealloc;

@end

