//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GADOAdType : NSObject
{
    _Bool _isRewardBasedVideoAd;
    _Bool _isInterstitial;
    struct GADOAdSize _adSize;
}

+ (id)interstitialAdType;
+ (id)bannerAdTypeForSize:(struct GADOAdSize)arg1;
@property(nonatomic) struct GADOAdSize adSize; // @synthesize adSize=_adSize;
@property(readonly, nonatomic) _Bool isInterstitial; // @synthesize isInterstitial=_isInterstitial;
- (id)description;
- (_Bool)isValid;
- (_Bool)isRewardBasedVideoAd;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initForRewardBasedVideoAd;
- (id)initForInterstitial;
- (id)initWithAdSize:(struct GADOAdSize)arg1;
- (id)init;

@end

