//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADOAdReward, GADORewardBasedVideoAd, NSError;

@protocol GADRewardBasedVideoAdDelegate <NSObject>
- (void)rewardBasedVideoAd:(GADORewardBasedVideoAd *)arg1 didRewardUserWithReward:(GADOAdReward *)arg2;

@optional
- (void)rewardBasedVideoAdMetadataDidChange:(GADORewardBasedVideoAd *)arg1;
- (void)rewardBasedVideoAdWillLeaveApplication:(GADORewardBasedVideoAd *)arg1;
- (void)rewardBasedVideoAdDidClose:(GADORewardBasedVideoAd *)arg1;
- (void)rewardBasedVideoAdDidCompletePlaying:(GADORewardBasedVideoAd *)arg1;
- (void)rewardBasedVideoAdDidStartPlaying:(GADORewardBasedVideoAd *)arg1;
- (void)rewardBasedVideoAdDidOpen:(GADORewardBasedVideoAd *)arg1;
- (void)rewardBasedVideoAdDidReceiveAd:(GADORewardBasedVideoAd *)arg1;
- (void)rewardBasedVideoAd:(GADORewardBasedVideoAd *)arg1 didFailToLoadWithError:(NSError *)arg2;
@end

