//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HTMLToken.h"

@class NSMutableString, NSString;

@interface HTMLCharacterToken : HTMLToken
{
    NSMutableString *_characters;
}

@property(copy, nonatomic) NSString *characters; // @synthesize characters=_characters;
- (void).cxx_destruct;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)tokenBySplitingLeadingWhiteSpace;
- (void)trimFormIndex:(unsigned long long)arg1;
- (void)trimLeadingWhitespace;
- (void)retainLeadingWhitespace;
- (_Bool)isEmpty;
- (_Bool)isWhitespaceToken;
- (void)appendString:(id)arg1;
- (id)initWithString:(id)arg1;

@end

