//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableDictionary.h"

@class NSMutableArray;

@interface HTMLOrderedDictionary : NSMutableDictionary
{
    NSMutableDictionary *_dictionary;
    NSMutableArray *_keys;
}

- (void).cxx_destruct;
- (id)mutableCopy;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (id)reverseKeyEnumerator;
- (id)keyEnumerator;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (void)setObject:(id)arg1 atIndexedSubscript:(unsigned long long)arg2;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
- (unsigned long long)indexOfKey:(id)arg1;
- (void)replaceKey:(id)arg1 withKey:(id)arg2;
- (void)replaceKeyValueAtIndex:(unsigned long long)arg1 withObject:(id)arg2 andKey:(id)arg3;
- (void)removeObjectAtIndex:(unsigned long long)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2 atIndex:(unsigned long long)arg3;
- (id)objectAtIndex:(unsigned long long)arg1;
- (unsigned long long)count;
- (void)removeObjectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)objectForKey:(id)arg1;
- (id)initWithObjects:(id)arg1 forKeys:(id)arg2;
- (id)initWithCapacity:(unsigned long long)arg1;
- (id)init;

@end

