//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HTMLElement.h"

@class HTMLDocumentFragment;

@interface HTMLTemplate : HTMLElement
{
    HTMLDocumentFragment *_content;
}

@property(retain, nonatomic) HTMLDocumentFragment *content; // @synthesize content=_content;
- (void).cxx_destruct;
- (id)childNodes;
- (void)setOwnerDocument:(id)arg1;
- (id)init;

@end

