//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSEnumerator.h"

@class HTMLNode;

@interface HTMLNodeIterator : NSEnumerator
{
    HTMLNode *_root;
    _Bool _pointerBeforeReferenceNode;
    HTMLNode *_referenceNode;
    unsigned long long _whatToShow;
    id <HTMLNodeFilter> _filter;
}

@property(readonly, nonatomic) id <HTMLNodeFilter> filter; // @synthesize filter=_filter;
@property(readonly, nonatomic) unsigned long long whatToShow; // @synthesize whatToShow=_whatToShow;
@property(readonly, nonatomic) _Bool pointerBeforeReferenceNode; // @synthesize pointerBeforeReferenceNode=_pointerBeforeReferenceNode;
@property(readonly, nonatomic) HTMLNode *referenceNode; // @synthesize referenceNode=_referenceNode;
@property(readonly, nonatomic) HTMLNode *root; // @synthesize root=_root;
- (void).cxx_destruct;
- (id)nextObject;
- (id)previousNode;
- (id)nextNode;
- (id)traverseInDirection:(short)arg1;
- (void)runRemovingStepsForNode:(id)arg1 withOldParent:(id)arg2 andOldPreviousSibling:(id)arg3;
- (void)dealloc;
- (id)initWithNode:(id)arg1 showOptions:(unsigned long long)arg2 filter:(id)arg3;
- (id)initWithNode:(id)arg1 filter:(id)arg2;
- (id)initWithNode:(id)arg1;

@end

