//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HTMLTagToken.h"

@interface HTMLStartTagToken : HTMLTagToken
{
}

- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithTagName:(id)arg1 attributes:(id)arg2;
- (id)initWithTagName:(id)arg1;

@end

