//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HTMLToken.h"

@class NSMutableString, NSString;

@interface HTMLDOCTYPEToken : HTMLToken
{
    NSMutableString *_name;
    _Bool _forceQuirks;
    NSMutableString *_publicIdentifier;
    NSMutableString *_systemIdentifier;
}

@property(nonatomic) _Bool forceQuirks; // @synthesize forceQuirks=_forceQuirks;
@property(retain, nonatomic) NSMutableString *systemIdentifier; // @synthesize systemIdentifier=_systemIdentifier;
@property(retain, nonatomic) NSMutableString *publicIdentifier; // @synthesize publicIdentifier=_publicIdentifier;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (void)appendStringToSystemIdentifier:(id)arg1;
- (void)appendStringToPublicIdentifier:(id)arg1;
- (void)appendStringToName:(id)arg1;
- (id)initWithName:(id)arg1;
- (id)init;

@end

