//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HTMLToken.h"

@class NSString;

@interface HTMLParseErrorToken : HTMLToken
{
    NSString *_code;
    NSString *_details;
    unsigned long long _location;
}

@property(readonly, nonatomic) unsigned long long location; // @synthesize location=_location;
@property(readonly, nonatomic) NSString *details; // @synthesize details=_details;
@property(readonly, nonatomic) NSString *code; // @synthesize code=_code;
- (void).cxx_destruct;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithCode:(id)arg1 details:(id)arg2 location:(unsigned long long)arg3;

@end

