//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSMutableArray, NSMutableAttributedString, UIActivityIndicatorView, UIButton, UIProgressView, UITextView, UIView;

@interface InstallViewController : UIViewController
{
    UIActivityIndicatorView *_activityIndicatorView;
    UIProgressView *_progressView;
    UIView *_teleprompterView;
    NSMutableArray *_teleprompterLabels;
    UIButton *_completeButton;
    UIButton *_showDetailsButton;
    UIButton *_hideDetailsButton;
    UIView *_detailsView;
    UITextView *_detailsTextView;
    NSMutableAttributedString *_detailsAttributedString;
    int _returnButtonAction;
}

- (void).cxx_destruct;
- (void)viewDidLayoutSubviews;
- (void)hideDetails:(id)arg1;
- (void)showDetails:(id)arg1;
- (void)completeButtonTapped:(id)arg1;
- (void)updateCompleteButton;
- (void)pushText:(id)arg1;
- (void)setProgress:(float)arg1 animated:(_Bool)arg2;
@property(nonatomic) float progress;
- (id)transformAttributedString:(id)arg1;
- (void)viewDidLoad;

@end

