//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "RATreeViewDataSource.h"
#import "RATreeViewDelegate.h"

@class NSArray, NSString, RATreeView;

@interface InstalledContentsViewController : UIViewController <RATreeViewDataSource, RATreeViewDelegate>
{
    RATreeView *_treeView;
    NSArray *_filesList;
    NSString *_packageId;
}

@property(retain, nonatomic) NSString *packageId; // @synthesize packageId=_packageId;
- (void).cxx_destruct;
- (void)treeView:(id)arg1 didSelectRowForItem:(id)arg2;
- (id)treeView:(id)arg1 cellForItem:(id)arg2;
- (id)treeView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;
- (long long)treeView:(id)arg1 numberOfChildrenOfItem:(id)arg2;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

