//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface LNForwardingDelegate : NSObject
{
    id _forwardedDelegate;
}

@property(nonatomic) __weak id forwardedDelegate; // @synthesize forwardedDelegate=_forwardedDelegate;
- (void).cxx_destruct;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (_Bool)respondsToSelector:(SEL)arg1;

@end

