//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, UIImage, UIViewController;

@interface LNPopupItem : NSObject
{
    float _progress;
    NSString *_accessibilityImageLabel;
    NSString *_accessibilityProgressLabel;
    NSString *_accessibilityProgressValue;
    NSString *_title;
    NSString *_subtitle;
    UIImage *_image;
    NSArray *_leftBarButtonItems;
    NSArray *_rightBarButtonItems;
    id <_LNPopupItemDelegate> _itemDelegate;
    UIViewController *_containerController;
}

+ (void)load;
@property(nonatomic, getter=_containerController, setter=_setContainerController:) __weak UIViewController *containerController; // @synthesize containerController=_containerController;
@property(nonatomic, getter=_itemDelegate, setter=_setItemDelegate:) __weak id <_LNPopupItemDelegate> itemDelegate; // @synthesize itemDelegate=_itemDelegate;
@property(copy, nonatomic) NSArray *rightBarButtonItems; // @synthesize rightBarButtonItems=_rightBarButtonItems;
@property(copy, nonatomic) NSArray *leftBarButtonItems; // @synthesize leftBarButtonItems=_leftBarButtonItems;
@property(nonatomic) float progress; // @synthesize progress=_progress;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *accessibilityProgressValue; // @synthesize accessibilityProgressValue=_accessibilityProgressValue;
@property(copy, nonatomic) NSString *accessibilityProgressLabel; // @synthesize accessibilityProgressLabel=_accessibilityProgressLabel;
@property(copy, nonatomic) NSString *accessibilityImageLabel; // @synthesize accessibilityImageLabel=_accessibilityImageLabel;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (id)init;

@end

