//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIViewControllerPreviewingDelegate.h"
#import "_LNPopupBarDelegate.h"
#import "_LNPopupItemDelegate.h"

@class LNPopupBar, LNPopupContentView, LNPopupItem, NSLayoutConstraint, NSString, UIScrollView, UIView, UIViewController;

@interface LNPopupController : NSObject <_LNPopupItemDelegate, UIViewControllerPreviewingDelegate, _LNPopupBarDelegate>
{
    LNPopupItem *_currentPopupItem;
    UIViewController *_currentContentController;
    UIView *_popupShadowView;
    UIView *_popupScreenshotView;
    _Bool _dismissGestureStarted;
    double _dismissStartingOffset;
    double _dismissScrollViewStartingContentOffset;
    unsigned long long _stateBeforeDismissStarted;
    _Bool _dismissalOverride;
    _Bool _forceTouchOverride;
    struct CGRect _cachedDefaultFrame;
    struct UIEdgeInsets _cachedInsets;
    struct CGRect _cachedOpenPopupFrame;
    double _statusBarThresholdDir;
    double _bottomBarOffset;
    NSLayoutConstraint *_popupCloseButtonTopConstraint;
    NSLayoutConstraint *_popupCloseButtonHorizontalConstraint;
    id <UIViewControllerPreviewing> _previewingContext;
    UIView *_bottomBar;
    LNPopupBar *_popupBar;
    LNPopupContentView *_popupContentView;
    UIScrollView *_popupContentContainerView;
    unsigned long long _popupControllerState;
    unsigned long long _popupControllerTargetState;
    UIViewController *_containerController;
    double _lastSeenMovement;
    UIViewController *_effectiveStatusBarUpdateController;
    struct CGPoint _lastPopupBarLocation;
}

@property(nonatomic) __weak UIViewController *effectiveStatusBarUpdateController; // @synthesize effectiveStatusBarUpdateController=_effectiveStatusBarUpdateController;
@property(nonatomic) double lastSeenMovement; // @synthesize lastSeenMovement=_lastSeenMovement;
@property(nonatomic) struct CGPoint lastPopupBarLocation; // @synthesize lastPopupBarLocation=_lastPopupBarLocation;
@property(nonatomic) __weak UIViewController *containerController; // @synthesize containerController=_containerController;
@property(nonatomic) unsigned long long popupControllerTargetState; // @synthesize popupControllerTargetState=_popupControllerTargetState;
@property(nonatomic) unsigned long long popupControllerState; // @synthesize popupControllerState=_popupControllerState;
@property(retain, nonatomic) UIScrollView *popupContentContainerView; // @synthesize popupContentContainerView=_popupContentContainerView;
@property(retain, nonatomic) LNPopupContentView *popupContentView; // @synthesize popupContentView=_popupContentView;
@property(retain, nonatomic) LNPopupBar *popupBar; // @synthesize popupBar=_popupBar;
@property(nonatomic) __weak UIView *bottomBar; // @synthesize bottomBar=_bottomBar;
- (void).cxx_destruct;
- (void)_popupBarStyleDidChange:(id)arg1;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint)arg2;
- (void)_applicationWillEnterForeground;
- (void)_applicationDidEnterBackground;
- (void)dismissPopupBarAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)closePopupAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)openPopupAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)presentPopupBarAnimated:(_Bool)arg1 openPopup:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_cleanupGestureRecognizersForController:(id)arg1;
- (void)_fixupGestureRecognizersForController:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (id)popupScreenshotView;
- (id)popupShadowView;
@property(readonly, nonatomic) LNPopupBar *popupBarStorage;
- (void)_setUpCloseButtonForPopupContentView;
- (void)_repositionPopupCloseButton;
- (id)_view:(id)arg1 selfOrSuperviewKindOfClass:(Class)arg2;
- (void)_movePopupBarAndContentToBottomBarSuperview;
- (void)_configurePopupBarFromBottomBar;
- (void)_reconfigureContentWithOldContentController:(id)arg1 newContentController:(id)arg2;
- (void)_popupItem:(id)arg1 didChangeValueForKey:(id)arg2;
- (void)_reconfigure_rightBarButtonItems;
- (void)_reconfigure_leftBarButtonItems;
- (void)_reconfigureBarItems;
- (void)_reconfigure_accessibilityProgressValue;
- (void)_reconfigure_accessibilityProgressLabel;
- (void)_reconfigure_accessibilityImageLabel;
- (void)_reconfigure_accessibilityHint;
- (void)_reconfigure_accessibilityLavel;
- (void)_reconfigure_progress;
- (void)_reconfigure_image;
- (void)_reconfigure_subtitle;
- (void)_reconfigure_title;
- (void)_closePopupContent;
- (long long)positionForBar:(id)arg1;
- (void)_popupBarPresentationByUserPanGestureHandler:(id)arg1;
- (void)_popupBarPresentationByUserPanGestureHandler_endedOrCancelled:(id)arg1;
- (void)_popupBarPresentationByUserPanGestureHandler_changed:(id)arg1;
- (double)rubberbandFromHeight:(double)arg1;
- (void)_popupBarPresentationByUserPanGestureHandler_began:(id)arg1;
- (void)_popupBarTapGestureRecognized:(id)arg1;
- (void)_popupBarLongPressGestureRecognized:(id)arg1;
- (void)_transitionToState:(unsigned long long)arg1 animated:(_Bool)arg2 useSpringAnimation:(_Bool)arg3 allowPopupBarAlphaModification:(_Bool)arg4 completion:(CDUnknownBlockType)arg5 transitionOriginatedByUser:(_Bool)arg6;
- (void)_setContentToState:(unsigned long long)arg1;
- (double)_percentFromPopupBarForBottomBarDisplacement;
- (double)_percentFromPopupBar;
- (void)_repositionPopupContentMovingBottomBar:(_Bool)arg1;
- (struct CGRect)_frameForClosedPopupBar;
- (struct CGRect)_frameForOpenPopupBar;
- (id)initWithContainerViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

