//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIView, UIVisualEffectView, __LNChevronView;

@interface LNPopupCloseButton : UIButton
{
    UIVisualEffectView *_effectView;
    UIView *_highlightView;
    unsigned long long _style;
    __LNChevronView *_chevronView;
}

@property(readonly, nonatomic) unsigned long long style; // @synthesize style=_style;
- (void).cxx_destruct;
- (void)_setButtonContainerTransitioning;
- (void)_setButtonContainerStationary;
- (struct CGSize)intrinsicContentSize;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)_setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)_didTouchCancel;
- (void)_didTouchUp;
- (void)_didTouchDragEnter;
- (void)_didTouchDragExit;
- (void)_didTouchDown;
- (void)_setupForCircularButton;
- (void)_setupForChevronButton;
@property(readonly, nonatomic) UIVisualEffectView *backgroundView;
- (id)initWithStyle:(unsigned long long)arg1;

@end

