//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIAppearanceContainer.h"

@class LNPopupCustomBarViewController, LNPopupItem, NSArray, NSDictionary, NSString, UIColor, UIImage, UIImageView, UILabel<__MarqueeLabelType>, UILongPressGestureRecognizer, UIProgressView, UITapGestureRecognizer, UIToolbar, UIVisualEffectView;

@interface LNPopupBar : UIView <UIAppearanceContainer>
{
    unsigned long long _resolvedStyle;
    UIVisualEffectView *_backgroundView;
    _Bool _delaysBarButtonItemLayout;
    UIView *_titlesView;
    UILabel<__MarqueeLabelType> *_titleLabel;
    UILabel<__MarqueeLabelType> *_subtitleLabel;
    _Bool _needsLabelsLayout;
    UIColor *_userTintColor;
    UIColor *_userBackgroundColor;
    long long _actualBackgroundStyle;
    UIView *_shadowView;
    UIView *_separatorView;
    NSArray *_progressViewVerticalConstraints;
    _Bool _inheritsVisualStyleFromDockingView;
    _Bool _isInlineWithTabBar;
    _Bool _translucent;
    _Bool _marqueeScrollEnabled;
    _Bool _coordinateMarqueeScroll;
    long long _userBackgroundStyle;
    UIColor *_userBarTintColor;
    LNPopupItem *_popupItem;
    NSArray *_leftBarButtonItems;
    NSArray *_rightBarButtonItems;
    UIImageView *_imageView;
    unsigned long long _barStyle;
    double _tabBarHeight;
    unsigned long long _progressViewStyle;
    NSDictionary *_titleTextAttributes;
    NSDictionary *_subtitleTextAttributes;
    long long _barItemsSemanticContentAttribute;
    UITapGestureRecognizer *_popupOpenGestureRecognizer;
    UILongPressGestureRecognizer *_barHighlightGestureRecognizer;
    id <LNPopupBarPreviewingDelegate> _previewingDelegate;
    LNPopupCustomBarViewController *_customBarViewController;
    long long _systemBarStyle;
    UIColor *_systemTintColor;
    UIColor *_systemBarTintColor;
    UIColor *_systemBackgroundColor;
    UIColor *_systemShadowColor;
    id <_LNPopupBarDelegate> __barDelegate;
    NSString *_title;
    NSString *_subtitle;
    UIImage *_image;
    UIToolbar *_toolbar;
    UIView *_highlightView;
    UIProgressView *_progressView;
    NSString *_accessibilityCenterLabel;
    NSString *_accessibilityCenterHint;
    NSString *_accessibilityImageLabel;
    NSString *_accessibilityProgressLabel;
    NSString *_accessibilityProgressValue;
}

@property(copy, nonatomic) NSString *accessibilityProgressValue; // @synthesize accessibilityProgressValue=_accessibilityProgressValue;
@property(copy, nonatomic) NSString *accessibilityProgressLabel; // @synthesize accessibilityProgressLabel=_accessibilityProgressLabel;
@property(copy, nonatomic) NSString *accessibilityImageLabel; // @synthesize accessibilityImageLabel=_accessibilityImageLabel;
@property(copy, nonatomic) NSString *accessibilityCenterHint; // @synthesize accessibilityCenterHint=_accessibilityCenterHint;
@property(copy, nonatomic) NSString *accessibilityCenterLabel; // @synthesize accessibilityCenterLabel=_accessibilityCenterLabel;
@property(retain, nonatomic) UIProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UIView *highlightView; // @synthesize highlightView=_highlightView;
@property(retain, nonatomic) UIToolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) __weak id <_LNPopupBarDelegate> _barDelegate; // @synthesize _barDelegate=__barDelegate;
@property(retain, nonatomic) UIColor *systemShadowColor; // @synthesize systemShadowColor=_systemShadowColor;
@property(retain, nonatomic) UIColor *systemBackgroundColor; // @synthesize systemBackgroundColor=_systemBackgroundColor;
@property(retain, nonatomic) UIColor *systemBarTintColor; // @synthesize systemBarTintColor=_systemBarTintColor;
@property(retain, nonatomic) UIColor *systemTintColor; // @synthesize systemTintColor=_systemTintColor;
@property(nonatomic) long long systemBarStyle; // @synthesize systemBarStyle=_systemBarStyle;
@property(retain, nonatomic) LNPopupCustomBarViewController *customBarViewController; // @synthesize customBarViewController=_customBarViewController;
@property(nonatomic) __weak id <LNPopupBarPreviewingDelegate> previewingDelegate; // @synthesize previewingDelegate=_previewingDelegate;
@property(retain, nonatomic) UILongPressGestureRecognizer *barHighlightGestureRecognizer; // @synthesize barHighlightGestureRecognizer=_barHighlightGestureRecognizer;
@property(retain, nonatomic) UITapGestureRecognizer *popupOpenGestureRecognizer; // @synthesize popupOpenGestureRecognizer=_popupOpenGestureRecognizer;
@property(nonatomic) _Bool coordinateMarqueeScroll; // @synthesize coordinateMarqueeScroll=_coordinateMarqueeScroll;
@property(nonatomic) _Bool marqueeScrollEnabled; // @synthesize marqueeScrollEnabled=_marqueeScrollEnabled;
@property(nonatomic) long long barItemsSemanticContentAttribute; // @synthesize barItemsSemanticContentAttribute=_barItemsSemanticContentAttribute;
@property(copy, nonatomic) NSDictionary *subtitleTextAttributes; // @synthesize subtitleTextAttributes=_subtitleTextAttributes;
@property(copy, nonatomic) NSDictionary *titleTextAttributes; // @synthesize titleTextAttributes=_titleTextAttributes;
@property(nonatomic, getter=isTranslucent) _Bool translucent; // @synthesize translucent=_translucent;
@property(nonatomic) unsigned long long progressViewStyle; // @synthesize progressViewStyle=_progressViewStyle;
@property(nonatomic) double tabBarHeight; // @synthesize tabBarHeight=_tabBarHeight;
@property(nonatomic) _Bool isInlineWithTabBar; // @synthesize isInlineWithTabBar=_isInlineWithTabBar;
@property(nonatomic) unsigned long long barStyle; // @synthesize barStyle=_barStyle;
@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(copy, nonatomic) NSArray *rightBarButtonItems; // @synthesize rightBarButtonItems=_rightBarButtonItems;
@property(copy, nonatomic) NSArray *leftBarButtonItems; // @synthesize leftBarButtonItems=_leftBarButtonItems;
@property(nonatomic) __weak LNPopupItem *popupItem; // @synthesize popupItem=_popupItem;
@property(nonatomic) _Bool inheritsVisualStyleFromDockingView; // @synthesize inheritsVisualStyleFromDockingView=_inheritsVisualStyleFromDockingView;
- (void).cxx_destruct;
- (void)dealloc;
- (void)_removeAnimationFromBarItems;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_updateViewsAfterCustomBarViewControllerUpdate;
- (void)_layoutBarButtonItems;
- (void)_delayBarButtonLayout;
- (void)_setTitleViewMarqueesPaused:(_Bool)arg1;
- (void)_setTitleLableFontsAccordingToBarStyleAndTint;
- (void)_layoutImageView;
- (void)_setNeedsTitleLayout;
- (void)_updateAccessibility;
- (void)_layoutTitles;
- (void)_updateTitleInsetsForProminentBar:(struct UIEdgeInsets *)arg1;
- (void)_updateTitleInsetsForCompactBar:(struct UIEdgeInsets *)arg1;
- (void)_getLeftmostView:(id *)arg1 rightmostView:(id *)arg2 fromBarButtonItems:(id)arg3;
- (id)_viewForBarButtonItem:(id)arg1;
- (id)_newMarqueeLabel;
- (void)setSemanticContentAttribute:(long long)arg1;
- (void)setBackgroundColor:(id)arg1;
- (void)_internalSetBackgroundColor:(id)arg1;
- (id)backgroundColor;
@property(retain, nonatomic) UIColor *barTintColor; // @synthesize barTintColor=_userBarTintColor;
- (void)_internalSetBarTintColor:(id)arg1;
- (void)setTintColor:(id)arg1;
- (id)tintColor;
@property(nonatomic) long long backgroundStyle; // @synthesize backgroundStyle=_userBackgroundStyle;
- (void)_innerSetBackgroundStyle:(long long)arg1;
- (void)layoutSubviews;
- (void)_updateProgressViewWithStyle:(unsigned long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setHidden:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

