//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class LNPopupBar;

@interface LNPopupCustomBarViewController : UIViewController
{
    LNPopupBar *_containingPopupBar;
}

@property(nonatomic) __weak LNPopupBar *containingPopupBar; // @synthesize containingPopupBar=_containingPopupBar;
- (void).cxx_destruct;
- (void)popupItemDidUpdate;
@property(nonatomic) struct CGSize preferredContentSize; // @dynamic preferredContentSize;
@property(readonly, nonatomic) _Bool wantsDefaultPanGestureRecognizer;
@property(readonly, nonatomic) _Bool wantsDefaultTapGestureRecognizer;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

