//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FCModel.h"

#import "DatabaseModelProtocol.h"

@class NSDate, NSString, NSURL;

@interface NewsArticle : FCModel <DatabaseModelProtocol>
{
    long long _id;
    NSString *_guid;
    NSString *_title;
    NSString *_body;
    NSURL *_url;
    NSDate *_date;
    NSDate *_firstSeenDate;
    NSDate *_userReadDate;
}

+ (id)articleFromDictionary:(id)arg1;
+ (id)createTableCommand;
@property(retain, nonatomic) NSDate *userReadDate; // @synthesize userReadDate=_userReadDate;
@property(retain, nonatomic) NSDate *firstSeenDate; // @synthesize firstSeenDate=_firstSeenDate;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *body; // @synthesize body=_body;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *guid; // @synthesize guid=_guid;
@property(nonatomic) long long id; // @synthesize id=_id;
- (void).cxx_destruct;
- (void)markRead;
- (void)updateFromDictionary:(id)arg1 date:(id)arg2;
- (id)initWithDictionary:(id)arg1 date:(id)arg2 guid:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

