//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UIViewControllerPreviewingDelegate.h"

@class NSArray, NSString, UIActivityIndicatorView, UICollectionView;

@interface NewsArticlesViewController : UIViewController <UICollectionViewDataSource, UICollectionViewDelegate, UIViewControllerPreviewingDelegate>
{
    UICollectionView *_collectionView;
    UIActivityIndicatorView *_activityIndicatorView;
    _Bool _isLoading;
    _Bool _presentNextURLCommittedModally;
    NSArray *_articles;
}

@property(retain, nonatomic) NSArray *articles; // @synthesize articles=_articles;
- (void).cxx_destruct;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)loadArticles;
- (void)didMoveToParentViewController:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

