//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class NewsArticle, UILabel, UIView;

@interface NewsArticleCollectionViewCell : UICollectionViewCell
{
    NewsArticle *_article;
    UIView *_cardView;
    UILabel *_titleLabel;
    UILabel *_dateLabel;
    UILabel *_excerptLabel;
    UIView *_unreadView;
}

@property(nonatomic) __weak UIView *unreadView; // @synthesize unreadView=_unreadView;
@property(nonatomic) __weak UILabel *excerptLabel; // @synthesize excerptLabel=_excerptLabel;
@property(nonatomic) __weak UILabel *dateLabel; // @synthesize dateLabel=_dateLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak UIView *cardView; // @synthesize cardView=_cardView;
@property(retain, nonatomic) NewsArticle *article; // @synthesize article=_article;
- (void).cxx_destruct;
- (void)setHighlighted:(_Bool)arg1;
- (void)tintColorDidChange;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;

@end

