//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArray.h"

@interface NSArray (Functional)
- (id)filtered:(CDUnknownBlockType)arg1;
- (id)flatMapped:(CDUnknownBlockType)arg1;
- (id)mapped:(CDUnknownBlockType)arg1;
- (id)__iterateOnElement:(CDUnknownBlockType)arg1;
@end

