//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (NSHash_AdditionalHashingAlgorithms)
- (id)toHexString:(char *)arg1 length:(unsigned int)arg2;
- (id)SHA512String;
- (id)SHA512;
- (id)SHA256String;
- (id)SHA256;
- (id)SHA1String;
- (id)SHA1;
- (id)MD5String;
- (id)MD5;
@end

