//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSScanner.h"

@interface NSScanner (HTMLColors)
- (_Bool)cmr_scanFloatQuad:(CDStruct_d2b197d1 *)arg1 scale:(CDStruct_d2b197d1)arg2;
- (_Bool)cmr_scanFloatTriple:(CDStruct_39925896 *)arg1 scale:(CDStruct_39925896)arg2;
- (_Bool)cmr_scanNum:(double *)arg1 scale:(double)arg2;
- (_Bool)cmr_scanHexTriple:(id *)arg1;
- (struct _NSRange)cmr_scanCharactersInSet:(id)arg1 maxLength:(unsigned long long)arg2 intoString:(id *)arg3;
- (_Bool)cmr_caseInsensitiveWithCleanup:(CDUnknownBlockType)arg1;
- (_Bool)cmr_resetScanLocationOnFailure:(CDUnknownBlockType)arg1;
- (void)cmr_skip;
- (void)cmr_skipCharactersInSet:(id)arg1;
- (struct _NSRange)cmr_rangeFromScanLocation;
- (void)cmr_withNoSkip:(CDUnknownBlockType)arg1;
- (void)cmr_withSkip:(id)arg1 run:(CDUnknownBlockType)arg2;
- (_Bool)scanW3CNamedColor:(id *)arg1;
- (_Bool)scanHexColor:(id *)arg1;
- (_Bool)scanHSLColor:(id *)arg1;
- (_Bool)scanGrayColor:(id *)arg1;
- (_Bool)scanRGBColor:(id *)arg1;
- (_Bool)scanCSSColor:(id *)arg1;
@end

