//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (NSHash_AdditionalHashingAlgorithms)
- (id)toHexString:(char *)arg1 length:(unsigned int)arg2;
- (unsigned int)UTF8Length;
- (id)SHA512Data;
- (id)SHA256Data;
- (id)SHA512;
- (id)SHA256;
- (id)SHA1Data;
- (id)SHA1;
- (id)MD5Data;
- (id)MD5;
@end

