//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "DepictionViewDelegate.h"
#import "MFMailComposeViewControllerDelegate.h"
#import "PackageQueueButtonDataProvider.h"
#import "UIScrollViewDelegate.h"
#import "WKNavigationDelegate.h"
#import "WKUIDelegate.h"

@class DepictionBaseView, NSLayoutConstraint, NSString, Package, PackageIconView, PackageQueueButton, UIBarButtonItem, UIButton, UIImageView, UILabel, UIScrollView, UIStackView, UIView, WKWebView;

@interface PackageViewController : UIViewController <MFMailComposeViewControllerDelegate, UIScrollViewDelegate, DepictionViewDelegate, WKNavigationDelegate, WKUIDelegate, PackageQueueButtonDataProvider>
{
    UIScrollView *_scrollView;
    UIView *_contentView;
    UILabel *_packageName;
    UILabel *_packageAuthor;
    PackageIconView *_packageIconView;
    PackageQueueButton *_downloadButton;
    PackageQueueButton *_navBarDownloadButton;
    PackageIconView *_packageNavBarIconView;
    UIButton *_shareButton;
    UIBarButtonItem *_navBarShareButtonItem;
    UIBarButtonItem *_navBarDownloadButtonItem;
    DepictionBaseView *_depictionView;
    WKWebView *_depictionWebView;
    DepictionBaseView *_depictionFooterView;
    NSString *_paymentProvider;
    NSString *_price;
    _Bool _purchased;
    _Bool _available;
    Package *_package;
    Package *_installedPackage;
    UIView *_depictionHeaderView;
    UIImageView *_depictionBackgroundShadow;
    UIImageView *_depictionBackgroundView;
    UIStackView *_packageInfoView;
    NSLayoutConstraint *_depictionHeaderImageViewHeight;
    NSLayoutConstraint *_contentViewHeight;
    NSLayoutConstraint *_contentViewWidth;
    NSLayoutConstraint *_downloadButtonWidth;
    double _depictionHeight;
    _Bool _allowNavbarUpdates;
    _Bool _hasDepictionHeader;
    double currentNavBarOpacity;
    _Bool _isUpdatingPurchaseStatus;
    _Bool _isPresentedModally;
    double _packageAdvertisementCount;
}

@property(nonatomic) double packageAdvertisementCount; // @synthesize packageAdvertisementCount=_packageAdvertisementCount;
@property(nonatomic) _Bool isPresentedModally; // @synthesize isPresentedModally=_isPresentedModally;
@property(nonatomic) double depictionHeight; // @synthesize depictionHeight=_depictionHeight;
@property(retain, nonatomic) Package *package; // @synthesize package=_package;
- (void).cxx_destruct;
- (id)previewActionItems;
- (void)checkLegacyPurchaseStatus:(id)arg1;
- (void)updatePurchaseStatus;
- (void)dismiss;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(long long)arg2 error:(id)arg3;
- (void)sharePackage:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)subviewHeightChanged;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)webView:(id)arg1 commitPreviewingViewController:(id)arg2;
- (id)webView:(id)arg1 previewingViewControllerForElement:(id)arg2 defaultActions:(id)arg3;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)versionTooLow;
- (void)reloadData;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

