//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"
#import "UIGestureRecognizerDelegate.h"
#import "UISearchBarDelegate.h"
#import "UISearchResultsUpdating.h"
#import "UIViewControllerPreviewingDelegate.h"

@class NSArray, NSString, Repo, UIBarButtonItem, UICollectionView, UISearchController;

@interface PackageListViewController : UIViewController <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, UISearchBarDelegate, UISearchResultsUpdating, UIGestureRecognizerDelegate, UIViewControllerPreviewingDelegate>
{
    UICollectionView *_collectionView;
    UIBarButtonItem *_downloadsButton;
    _Bool _showSearchField;
    _Bool _showUpdates;
    _Bool _showWishlist;
    NSString *_packagesLoadIdentifier;
    Repo *_repoContext;
    NSArray *_packages;
    NSArray *_availableUpdates;
    _Bool _displaySettings;
    struct _opaque_pthread_mutex_t _mutexLock;
    int _updatingCount;
    NSString *_localizableTitle;
    UISearchController *_searchController;
}

@property(retain, nonatomic) UISearchController *searchController; // @synthesize searchController=_searchController;
@property(retain, nonatomic) NSArray *packages; // @synthesize packages=_packages;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) Repo *repoContext; // @synthesize repoContext=_repoContext;
@property(retain, nonatomic) NSString *packagesLoadIdentifier; // @synthesize packagesLoadIdentifier=_packagesLoadIdentifier;
- (void).cxx_destruct;
- (void)showWishlist:(id)arg1;
- (void)changeSettings:(id)arg1;
- (void)sortPopup:(id)arg1;
- (void)toggleSettings:(id)arg1;
- (void)updateSearchResultsForSearchController:(id)arg1;
- (void)reloadData;
- (void)searchBarTextDidEndEditing:(id)arg1;
- (void)collectionView:(id)arg1 didDeselectItemAtIndexPath:(id)arg2;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)controllerForIndexPath:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (id)getImgWithColor:(id)arg1 andSize:(struct CGSize)arg2;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

