//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class Package, PackageStateBadgeView, UIImageView, UILabel, UIView;

@interface PackageCollectionViewCell : UICollectionViewCell
{
    UIImageView *_imageView;
    UILabel *_titleLabel;
    UILabel *_authorLabel;
    UILabel *_descriptionLabel;
    UIView *_separatorView;
    UIView *_unreadView;
    PackageStateBadgeView *stateBadgeView;
    _Bool _alwaysHidesSeparator;
    Package *_targetPackage;
    long long _item;
    long long _numberOfItems;
}

@property(nonatomic) _Bool alwaysHidesSeparator; // @synthesize alwaysHidesSeparator=_alwaysHidesSeparator;
@property(nonatomic) long long numberOfItems; // @synthesize numberOfItems=_numberOfItems;
@property(nonatomic) long long item; // @synthesize item=_item;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) UILabel *authorLabel; // @synthesize authorLabel=_authorLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) Package *targetPackage; // @synthesize targetPackage=_targetPackage;
- (void).cxx_destruct;
- (void)setHighlighted:(_Bool)arg1;
- (void)tintColorDidChange;
- (void)refreshState;
- (void)setTargetPackage:(id)arg1 isUnread:(_Bool)arg2;
- (void)layoutSubviews;
- (void)awakeFromNib;

@end

