//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIColor;

@interface PackageButton : UIButton
{
    double _alpha;
    UIColor *_tintColor;
    _Bool _isProminent;
}

@property(nonatomic, setter=setProminent:) _Bool isProminent; // @synthesize isProminent=_isProminent;
- (void).cxx_destruct;
- (void)setTitle:(id)arg1 forState:(unsigned long long)arg2;
- (void)_setAlpha:(double)arg1;
- (void)setEnabled:(_Bool)arg1;
- (void)updateStyle;
- (void)setTintColor:(id)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)layoutSubviews;
- (void)setup;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

