//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSObject<OS_dispatch_queue>;

@interface PackageListManager : NSObject
{
    NSArray *_installedPackages;
    NSArray *_allPackages;
    struct _opaque_pthread_mutex_t databaseLock;
    struct _opaque_pthread_mutex_t _changesDatabaseLock;
    NSObject<OS_dispatch_queue> *_databaseUpdateQueue;
    _Bool _isLoaded;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)markUpgradeAll:(id)arg1;
- (id)packagesForIdentifiers:(id)arg1;
- (id)packageFromURL:(id)arg1;
- (id)installedPackageWithIdentifier:(id)arg1;
- (id)newestPackageWithIdentifier:(id)arg1;
- (id)filteredPackagesForDisplay:(id)arg1;
- (id)packagesListForLoadIdentifier:(id)arg1 repoContext:(id)arg2 parseError:(id *)arg3 useCache:(_Bool)arg4 overridePackagesFile:(id)arg5;
- (id)packagesListForLoadIdentifier:(id)arg1 repoContext:(id)arg2;
- (id)dpkgDir;
- (id)packageFromDictionary:(id)arg1;
- (id)humanReadableCategory:(id)arg1;
- (void)loadAllPackages;
- (id)availableUpdates;
- (void)purgeCache;
- (void)waitForChangesDatabaseReady;
- (void)waitForReady;
- (id)init;

@end

