//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FCModel.h"

#import "DatabaseModelProtocol.h"

@class NSArray, NSDate, NSDictionary, NSMutableArray, NSString, NSURL;

@interface Package : FCModel <DatabaseModelProtocol>
{
    _Bool _essential;
    _Bool _commercial;
    _Bool _fromStatusFile;
    _Bool _isFirstKnownVersion;
    int _wantInfo;
    int _eFlag;
    int _status;
    long long _id;
    NSString *_guid;
    NSString *_package;
    NSString *_packageID;
    NSString *_name;
    NSString *_version;
    NSString *_architecture;
    NSString *_author;
    NSString *_maintainer;
    NSString *_section;
    NSString *_conflicts;
    NSString *_depends;
    NSString *_provides;
    NSString *_replaces;
    NSString *_packageDescription;
    NSString *_legacyDepiction;
    NSString *_depiction;
    NSString *_icon;
    NSString *_sourceFile;
    NSDictionary *_rawControl;
    NSArray *_tags;
    NSMutableArray *_allVersions;
    NSString *_filename;
    NSString *_size;
    NSURL *_packageFileURL;
    NSDate *_firstSeenDate;
    NSDate *_userReadDate;
}

+ (id)createTableCommand;
@property(nonatomic) _Bool isFirstKnownVersion; // @synthesize isFirstKnownVersion=_isFirstKnownVersion;
@property(retain, nonatomic) NSDate *userReadDate; // @synthesize userReadDate=_userReadDate;
@property(retain, nonatomic) NSDate *firstSeenDate; // @synthesize firstSeenDate=_firstSeenDate;
@property(retain, nonatomic) NSURL *packageFileURL; // @synthesize packageFileURL=_packageFileURL;
@property(retain, nonatomic) NSString *size; // @synthesize size=_size;
@property(retain, nonatomic) NSString *filename; // @synthesize filename=_filename;
@property(nonatomic) int status; // @synthesize status=_status;
@property(nonatomic) int eFlag; // @synthesize eFlag=_eFlag;
@property(nonatomic) int wantInfo; // @synthesize wantInfo=_wantInfo;
@property(nonatomic) _Bool fromStatusFile; // @synthesize fromStatusFile=_fromStatusFile;
@property(retain, nonatomic) NSMutableArray *allVersions; // @synthesize allVersions=_allVersions;
@property(retain, nonatomic) NSArray *tags; // @synthesize tags=_tags;
@property(nonatomic) _Bool commercial; // @synthesize commercial=_commercial;
@property(nonatomic) _Bool essential; // @synthesize essential=_essential;
@property(retain, nonatomic) NSDictionary *rawControl; // @synthesize rawControl=_rawControl;
@property(nonatomic) __weak NSString *sourceFile; // @synthesize sourceFile=_sourceFile;
@property(retain, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) NSString *depiction; // @synthesize depiction=_depiction;
@property(retain, nonatomic) NSString *legacyDepiction; // @synthesize legacyDepiction=_legacyDepiction;
@property(retain, nonatomic) NSString *packageDescription; // @synthesize packageDescription=_packageDescription;
@property(retain, nonatomic) NSString *replaces; // @synthesize replaces=_replaces;
@property(retain, nonatomic) NSString *provides; // @synthesize provides=_provides;
@property(retain, nonatomic) NSString *depends; // @synthesize depends=_depends;
@property(retain, nonatomic) NSString *conflicts; // @synthesize conflicts=_conflicts;
@property(retain, nonatomic) NSString *section; // @synthesize section=_section;
@property(retain, nonatomic) NSString *maintainer; // @synthesize maintainer=_maintainer;
@property(retain, nonatomic) NSString *author; // @synthesize author=_author;
@property(retain, nonatomic) NSString *architecture; // @synthesize architecture=_architecture;
@property(retain, nonatomic) NSString *version; // @synthesize version=_version;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *packageID; // @synthesize packageID=_packageID;
@property(retain, nonatomic) NSString *package; // @synthesize package=_package;
@property(retain, nonatomic) NSString *guid; // @synthesize guid=_guid;
@property(nonatomic) long long id; // @synthesize id=_id;
- (void).cxx_destruct;
- (void)markRead;
- (_Bool)isEqual:(id)arg1;
@property(readonly) unsigned long long hash;
- (id)sourceRepo;
- (_Bool)hasIcon;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

