//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSLayoutConstraint, PaymentProvider, UIStackView, UIViewController;

@interface PaymentAuthenticationBannerView : UIView
{
    UIStackView *stackView;
    NSLayoutConstraint *hairlineHeightConstraint;
    PaymentProvider *provider;
    UIViewController *_viewController;
}

@property(nonatomic) UIViewController *viewController; // @synthesize viewController=_viewController;
- (void).cxx_destruct;
- (void)buttonTapped;
- (void)didMoveToWindow;
- (id)initWithProvider:(id)arg1 bannerDictionary:(id)arg2 viewController:(id)arg3;

@end

