//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PaymentPackageInfo : NSObject
{
    _Bool _purchased;
    _Bool _available;
    NSString *_price;
}

+ (id)infoWithDictionary:(id)arg1;
@property(readonly, nonatomic, getter=isAvailable) _Bool available; // @synthesize available=_available;
@property(readonly, nonatomic, getter=isPurchased) _Bool purchased; // @synthesize purchased=_purchased;
@property(readonly, retain, nonatomic) NSString *price; // @synthesize price=_price;
- (void).cxx_destruct;
- (id)description;
- (id)initWithPrice:(id)arg1 purchased:(_Bool)arg2 available:(_Bool)arg3;

@end

