//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class PaymentProvider, UIActivityIndicatorView, UIImageView, UILabel;

@interface PaymentProviderTableViewCell : UITableViewCell
{
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UIImageView *_imageView;
    UIActivityIndicatorView *_loadingView;
    _Bool _authenticated;
    PaymentProvider *_provider;
}

@property(nonatomic, getter=isAuthenticated) _Bool authenticated; // @synthesize authenticated=_authenticated;
@property(retain, nonatomic) PaymentProvider *provider; // @synthesize provider=_provider;
- (void).cxx_destruct;
- (id)detailTextLabel;
- (id)textLabel;
- (void)_setImage:(id)arg1;
- (void)prepareForReuse;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

