//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DownloadOverrideProviding.h"

@class NSDictionary, NSString, NSURL;

@interface PaymentProvider : NSObject <DownloadOverrideProviding>
{
    _Bool isInfoFresh;
    _Bool isUserInfoFresh;
    NSURL *_baseURL;
    NSDictionary *_info;
    NSDictionary *_storedUserInfo;
}

+ (id)paymentSecretKeychain;
+ (id)tokenKeychain;
+ (void)makeRequest:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
+ (void)triggerListUpdateNotification;
@property(readonly, retain, nonatomic) NSDictionary *storedUserInfo; // @synthesize storedUserInfo=_storedUserInfo;
@property(readonly, retain, nonatomic) NSDictionary *info; // @synthesize info=_info;
@property(readonly, retain, nonatomic) NSURL *baseURL; // @synthesize baseURL=_baseURL;
- (void).cxx_destruct;
- (void)postRequestWithPath:(id)arg1 includeToken:(_Bool)arg2 includePaymentSecret:(_Bool)arg3 body:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)postRequestWithPath:(id)arg1 includeToken:(_Bool)arg2 includePaymentSecret:(_Bool)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)getRequestWithPath:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (_Bool)downloadURLForPackage:(id)arg1 fromRepo:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)initiatePurchaseForPackageIdentifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)getPackageInfoForIdentifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)invalidateSavedToken;
- (void)signOutWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)authenticateWithToken:(id)arg1 paymentSecret:(id)arg2;
- (void)fetchUserInfoFromCache:(_Bool)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)fetchInfoFromCache:(_Bool)arg1 completionHandler:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) NSURL *authenticationURL;
@property(readonly, nonatomic) NSString *authenticationToken;
@property(readonly, nonatomic) _Bool isAuthenticated;
@property(readonly, nonatomic) NSString *_cachePath;
- (void)_saveCache;
- (void)_loadCache;
- (id)initWithBaseURL:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

