//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RABatchChangeEntity : NSObject
{
    long long _type;
    long long _ranking;
    CDUnknownBlockType _updatesBlock;
}

+ (id)batchChangeEntityWithBlock:(CDUnknownBlockType)arg1 type:(long long)arg2 ranking:(long long)arg3;
@property(copy, nonatomic) CDUnknownBlockType updatesBlock; // @synthesize updatesBlock=_updatesBlock;
@property(nonatomic) long long ranking; // @synthesize ranking=_ranking;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (_Bool)destructiveOperation;
- (_Bool)constructiveOperation;
- (long long)compare:(id)arg1;

@end

