//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class RATreeView, UITableViewCell;

@protocol RATreeViewDataSource <NSObject>
- (id)treeView:(RATreeView *)arg1 child:(long long)arg2 ofItem:(id)arg3;
- (UITableViewCell *)treeView:(RATreeView *)arg1 cellForItem:(id)arg2;
- (long long)treeView:(RATreeView *)arg1 numberOfChildrenOfItem:(id)arg2;

@optional
- (_Bool)treeView:(RATreeView *)arg1 canEditRowForItem:(id)arg2;
- (void)treeView:(RATreeView *)arg1 commitEditingStyle:(long long)arg2 forRowForItem:(id)arg3;
@end

