//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class RATreeNodeCollectionController;

@protocol RATreeNodeCollectionControllerDataSource <NSObject>
- (id)treeNodeCollectionController:(RATreeNodeCollectionController *)arg1 child:(long long)arg2 ofItem:(id)arg3;
- (long long)treeNodeCollectionController:(RATreeNodeCollectionController *)arg1 numberOfChildrenForItem:(id)arg2;
@end

