//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "RATreeNodeCollectionControllerDataSource.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, RABatchChanges, RATreeNodeCollectionController, UIColor, UIScrollView, UITableView, UIVisualEffect;

@interface RATreeView : UIView <RATreeNodeCollectionControllerDataSource, UITableViewDataSource, UITableViewDelegate>
{
    _Bool _expandsChildRowsWhenRowExpands;
    _Bool _collapsesChildRowsWhenRowCollapses;
    int _rowsExpandingAnimation;
    int _rowsCollapsingAnimation;
    id <RATreeViewDataSource> _dataSource;
    id <RATreeViewDelegate> _delegate;
    UITableView *_tableView;
    RATreeNodeCollectionController *_treeNodeCollectionController;
    RABatchChanges *_batchChanges;
}

+ (long long)tableViewScrollPositionForTreeViewScrollPosition:(int)arg1;
+ (int)treeViewStyleForTableViewStyle:(long long)arg1;
+ (long long)tableViewStyleForTreeViewStyle:(int)arg1;
+ (long long)tableViewCellSeparatorStyleForTreeViewCellSeparatorStyle:(int)arg1;
+ (int)treeViewCellSeparatorStyleForTableViewSeparatorStyle:(long long)arg1;
+ (long long)tableViewRowAnimationForTreeViewRowAnimation:(int)arg1;
@property(retain, nonatomic) RABatchChanges *batchChanges; // @synthesize batchChanges=_batchChanges;
@property(retain, nonatomic) RATreeNodeCollectionController *treeNodeCollectionController; // @synthesize treeNodeCollectionController=_treeNodeCollectionController;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) int rowsCollapsingAnimation; // @synthesize rowsCollapsingAnimation=_rowsCollapsingAnimation;
@property(nonatomic) int rowsExpandingAnimation; // @synthesize rowsExpandingAnimation=_rowsExpandingAnimation;
@property(nonatomic) _Bool collapsesChildRowsWhenRowCollapses; // @synthesize collapsesChildRowsWhenRowCollapses=_collapsesChildRowsWhenRowCollapses;
@property(nonatomic) _Bool expandsChildRowsWhenRowExpands; // @synthesize expandsChildRowsWhenRowExpands=_expandsChildRowsWhenRowExpands;
@property(nonatomic) __weak id <RATreeViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <RATreeViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (id)itemsForIndexPaths:(id)arg1;
- (void)zoomToRect:(struct CGRect)arg1 animated:(_Bool)arg2;
- (void)flashScrollIndicators;
- (void)setZoomScale:(double)arg1 animated:(_Bool)arg2;
- (void)scrollRectToVisible:(struct CGRect)arg1 animated:(_Bool)arg2;
- (void)setContentOffset:(struct CGPoint)arg1 animated:(_Bool)arg2;
- (void)reloadRows;
- (void)reloadRowsForItems:(id)arg1 withRowAnimation:(int)arg2;
- (void)reloadData;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
@property(nonatomic, getter=isEditing) _Bool editing;
@property(nonatomic) _Bool allowsMultipleSelectionDuringEditing;
@property(nonatomic) _Bool allowsSelectionDuringEditing;
@property(nonatomic) _Bool allowsMultipleSelection;
@property(nonatomic) _Bool allowsSelection;
- (void)deselectRowForItem:(id)arg1 animated:(_Bool)arg2;
- (void)selectRowForItem:(id)arg1 animated:(_Bool)arg2 scrollPosition:(int)arg3;
- (id)itemsForSelectedRows;
- (id)itemForSelectedRow;
- (void)scrollToNearestSelectedRowAtScrollPosition:(int)arg1 animated:(_Bool)arg2;
- (void)scrollToRowForItem:(id)arg1 atScrollPosition:(int)arg2 animated:(_Bool)arg3;
@property(readonly, copy, nonatomic) NSArray *itemsForVisibleRows;
- (id)itemsForRowsInRect:(struct CGRect)arg1;
- (id)itemForRowAtPoint:(struct CGPoint)arg1;
- (id)itemForCell:(id)arg1;
- (id)visibleCells;
- (id)cellForItem:(id)arg1;
- (id)parentForItem:(id)arg1;
- (long long)levelForCell:(id)arg1;
- (long long)levelForCellForItem:(id)arg1;
- (_Bool)isCellExpanded:(id)arg1;
- (_Bool)isCellForItemExpanded:(id)arg1;
@property(retain, nonatomic) UIView *treeFooterView;
@property(retain, nonatomic) UIView *treeHeaderView;
- (id)dequeueReusableHeaderFooterViewWithIdentifier:(id)arg1;
- (void)registerClass:(Class)arg1 forHeaderFooterViewReuseIdentifier:(id)arg2;
- (void)registerNib:(id)arg1 forHeaderFooterViewReuseIdentifier:(id)arg2;
- (id)dequeueReusableCellWithIdentifier:(id)arg1;
- (void)registerClass:(Class)arg1 forCellReuseIdentifier:(id)arg2;
- (void)registerNib:(id)arg1 forCellReuseIdentifier:(id)arg2;
- (void)deleteItemsAtIndexes:(id)arg1 inParent:(id)arg2 withAnimation:(int)arg3;
- (void)insertItemsAtIndexes:(id)arg1 inParent:(id)arg2 withAnimation:(int)arg3;
- (void)endUpdates;
- (void)beginUpdates;
- (void)collapseRowForItem:(id)arg1 collapseChildren:(_Bool)arg2 withRowAnimation:(int)arg3;
- (void)collapseRowForItem:(id)arg1 withRowAnimation:(int)arg2;
- (void)collapseRowForItem:(id)arg1;
- (void)expandRowForItem:(id)arg1 expandChildren:(_Bool)arg2 withRowAnimation:(int)arg3;
- (void)expandRowForItem:(id)arg1 withRowAnimation:(int)arg2;
- (void)expandRowForItem:(id)arg1;
@property(retain, nonatomic) UIView *backgroundView;
@property(nonatomic) _Bool cellLayoutMarginsFollowReadableWidth;
@property(copy, nonatomic) UIVisualEffect *separatorEffect;
@property(nonatomic) struct UIEdgeInsets separatorInset;
@property(nonatomic) double estimatedRowHeight;
@property(nonatomic) double rowHeight;
@property(retain, nonatomic) UIColor *separatorColor;
@property(nonatomic) int separatorStyle;
@property(readonly, nonatomic) int style;
- (long long)numberOfRows;
@property(readonly, nonatomic) UIScrollView *scrollView;
- (void)awakeFromNib;
- (void)commonInitWithFrame:(struct CGRect)arg1 style:(int)arg2;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 style:(int)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;
- (void)removeItemAtIndex:(long long)arg1 inParent:(id)arg2 withAnimation:(int)arg3;
- (void)moveItemAtIndex:(long long)arg1 inParent:(id)arg2 toIndex:(long long)arg3 inParent:(id)arg4;
- (void)insertItemAtIndex:(long long)arg1 inParent:(id)arg2 withAnimation:(int)arg3;
- (void)expandCellForTreeNode:(id)arg1 expandChildren:(_Bool)arg2 withRowAnimation:(int)arg3;
- (void)expandCellForTreeNode:(id)arg1;
- (void)collapseCellForTreeNode:(id)arg1 collapseChildren:(_Bool)arg2 withRowAnimation:(int)arg3;
- (void)collapseCellForTreeNode:(id)arg1;
- (id)indexPathForItem:(id)arg1;
- (id)treeNodeForIndexPath:(id)arg1;
- (id)childrenForItem:(id)arg1;
- (void)setupTreeStructure;
- (id)treeNodeCollectionController:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;
- (long long)treeNodeCollectionController:(id)arg1 numberOfChildrenForItem:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)expandCellForTreeNode:(id)arg1 informDelegate:(_Bool)arg2;
- (void)collapseCellForTreeNode:(id)arg1 informDelegate:(_Bool)arg2;
- (void)tableView:(id)arg1 didUnhighlightRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didHighlightRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 performAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (_Bool)tableView:(id)arg1 canPerformAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (_Bool)tableView:(id)arg1 shouldShowMenuForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 editActionsForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willDeselectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (long long)tableView:(id)arg1 indentationLevelForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

