//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RATreeNodeItem : NSObject
{
    id _item;
    id _parent;
    long long _index;
    id <RATreeNodeItemDataSource> _dataSource;
}

@property(nonatomic) __weak id <RATreeNodeItemDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) long long index; // @synthesize index=_index;
@property(nonatomic) __weak id parent; // @synthesize parent=_parent;
@property(retain, nonatomic) id item; // @synthesize item=_item;
- (void).cxx_destruct;
- (id)initWithParent:(id)arg1 index:(long long)arg2;

@end

