//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class RATreeNodeItem;

@interface RATreeNode : NSObject
{
    _Bool _expanded;
    RATreeNodeItem *_lazyItem;
    CDUnknownBlockType _expandedBlock;
}

@property(copy, nonatomic) CDUnknownBlockType expandedBlock; // @synthesize expandedBlock=_expandedBlock;
@property(retain, nonatomic) RATreeNodeItem *lazyItem; // @synthesize lazyItem=_lazyItem;
- (void).cxx_destruct;
@property(nonatomic) _Bool expanded;
@property(readonly, nonatomic) id item;
- (id)initWithLazyItem:(id)arg1 expandedBlock:(CDUnknownBlockType)arg2;

@end

