//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface RepoManager : NSObject
{
    NSMutableArray *_repoList;
}

+ (id)sharedInstance;
@property(readonly, nonatomic) NSMutableArray *repoList; // @synthesize repoList=_repoList;
- (void).cxx_destruct;
- (void)writeListToFile;
- (_Bool)checkPackagesHash:(id)arg1 packagesFileName:(id)arg2 releaseKey:(id)arg3 hashType:(id)arg4;
- (void)_updateWithCompletion:(CDUnknownBlockType)arg1 forceUpdate:(_Bool)arg2 forceReload:(_Bool)arg3 isBackground:(_Bool)arg4;
- (void)updateWithCompletion:(CDUnknownBlockType)arg1 forceUpdate:(_Bool)arg2 forceReload:(_Bool)arg3 isBackground:(_Bool)arg4;
- (_Bool)repoRequiresUpdate:(id)arg1;
- (void)fetchFromURL:(id)arg1 withExtensionsUntilSuccess:(id)arg2 success:(CDUnknownBlockType)arg3 progress:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (id)fetchFromURL:(id)arg1 success:(CDUnknownBlockType)arg2 progress:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)checkUpdatesInBackgroundWithCompletion:(CDUnknownBlockType)arg1;
- (id)cachePrefixForRepo:(id)arg1;
@property(readonly, nonatomic) NSString *cachePrefix;
- (void)parseSourcesFile:(id)arg1;
- (void)parseListFile:(id)arg1;
- (void)parseRepoEntry:(id)arg1 atPath:(id)arg2 withTypes:(id)arg3 URIs:(id)arg4 suites:(id)arg5 components:(id)arg6;
- (id)repoWithSourceFile:(id)arg1;
- (id)repoWithURL:(id)arg1;
- (_Bool)hasRepoWithURL:(id)arg1;
- (void)addReposWithURLs:(id)arg1;
- (void)addRepoWithURL:(id)arg1;
- (id)init;

@end

