//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, UIImage;

@interface Repo : NSObject
{
    _Bool _isSecure;
    _Bool _isLoaded;
    NSString *_repoName;
    NSString *_repoDescription;
    NSString *_rawEntry;
    NSString *_rawURL;
    NSString *_suite;
    NSArray *_components;
    NSString *_entryFile;
    UIImage *_repoIcon;
    double _releaseProgress;
    double _releaseGPGProgress;
    double _packagesProgress;
    NSArray *_packages;
}

@property(retain, nonatomic) NSArray *packages; // @synthesize packages=_packages;
@property(nonatomic) double packagesProgress; // @synthesize packagesProgress=_packagesProgress;
@property(nonatomic) double releaseGPGProgress; // @synthesize releaseGPGProgress=_releaseGPGProgress;
@property(nonatomic) double releaseProgress; // @synthesize releaseProgress=_releaseProgress;
@property(retain, nonatomic) UIImage *repoIcon; // @synthesize repoIcon=_repoIcon;
@property(retain, nonatomic) NSString *entryFile; // @synthesize entryFile=_entryFile;
@property(retain, nonatomic) NSArray *components; // @synthesize components=_components;
@property(retain, nonatomic) NSString *suite; // @synthesize suite=_suite;
@property(retain, nonatomic) NSString *rawURL; // @synthesize rawURL=_rawURL;
@property(retain, nonatomic) NSString *rawEntry; // @synthesize rawEntry=_rawEntry;
@property(retain, nonatomic) NSString *repoDescription; // @synthesize repoDescription=_repoDescription;
@property(retain, nonatomic) NSString *repoName; // @synthesize repoName=_repoName;
@property(nonatomic) _Bool isLoaded; // @synthesize isLoaded=_isLoaded;
@property(nonatomic) _Bool isSecure; // @synthesize isSecure=_isSecure;
- (void).cxx_destruct;
- (_Bool)isFlat;
- (id)packagesURLForArch:(id)arg1;
- (id)primaryComponentURL;
- (id)displayURL;
- (id)repoURL;
- (id)URL;
- (id)displayName;
- (double)totalProgress;

@end

