//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSLayoutConstraint, UIView<SettingsHeaderViewDisplayable>;

@interface SettingsHeaderContainerView : UIView
{
    NSLayoutConstraint *hairlineHeightConstraint;
    NSLayoutConstraint *contentHeightConstraint;
    NSLayoutConstraint *contentBottomConstraint;
    UIView<SettingsHeaderViewDisplayable> *_headerView;
    double _elasticHeight;
}

@property(nonatomic) double elasticHeight; // @synthesize elasticHeight=_elasticHeight;
@property(retain, nonatomic) UIView<SettingsHeaderViewDisplayable> *headerView; // @synthesize headerView=_headerView;
- (void).cxx_destruct;
- (void)adjustHeaderViewHeight;
- (double)contentHeightForWidth:(double)arg1;
- (void)layoutSubviews;
- (void)didMoveToWindow;
- (id)initWithFrame:(struct CGRect)arg1;

@end

