//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "UIViewControllerPreviewingDelegate.h"

@class NSArray, NSString;

@interface SourcesViewController : UITableViewController <UIViewControllerPreviewingDelegate>
{
    NSArray *_sortedRepoList;
}

- (void).cxx_destruct;
- (void)reloadData;
- (void)reSortList;
- (void)refreshSources:(id)arg1;
- (void)refreshSourcesWithControl:(id)arg1 forceUpdate:(_Bool)arg2 forceReload:(_Bool)arg3;
- (void)presentAddClipboardSourcesPrompt:(id)arg1;
- (void)presentAddSourceEntryFieldWithURL:(id)arg1;
- (void)presentAddSourceEntryField;
- (void)handleSourceAddWithURLs:(id)arg1;
- (void)handleSourceAddWithURL:(id)arg1 bypassingFlagCheck:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)showFlaggedSourceWarningControllerForURL:(id)arg1;
- (void)isSourceFlagged:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)addSourceWithURL:(id)arg1 urlToAdd:(id)arg2;
- (void)addSource:(id)arg1;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)toggleEditing:(id)arg1;
- (id)getImgWithColor:(id)arg1 andSize:(struct CGSize)arg2;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)checkUpdatesInBackground;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)controllerForIndexPath:(id)arg1;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 performAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (_Bool)tableView:(id)arg1 canPerformAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (_Bool)tableView:(id)arg1 shouldShowMenuForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 trailingSwipeActionsConfigurationForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (_Bool)canEditRowAtIndexPath:(id)arg1;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

