//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSLayoutConstraint;

@interface SourceProgressIndicatorView : UIView
{
    UIView *barView;
    NSLayoutConstraint *barWidthConstraint;
    double _progress;
}

@property(nonatomic) double progress; // @synthesize progress=_progress;
- (void).cxx_destruct;
- (void)updateProgress;
- (void)tintColorDidChange;
- (id)initWithFrame:(struct CGRect)arg1;

@end

