//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSAttributedString, UIButton, UITextView;

@interface SourcesErrorsViewController : UIViewController
{
    UIButton *_dismissButton;
    NSAttributedString *_attributedString;
    UITextView *_errorOutputText;
}

@property(retain, nonatomic) UITextView *errorOutputText; // @synthesize errorOutputText=_errorOutputText;
@property(retain, nonatomic) NSAttributedString *attributedString; // @synthesize attributedString=_attributedString;
- (void).cxx_destruct;
- (long long)preferredStatusBarStyle;
- (id)transformAttributedString:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)dismiss:(id)arg1;
- (void)viewDidLoad;
- (void)viewDidAppear:(_Bool)arg1;

@end

