//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITabBarController.h"

@class UINavigationController;

@interface TabBarController : UITabBarController
{
    UINavigationController *_downloadsController;
    _Bool _popupIsPresented;
}

+ (id)singleton;
- (void).cxx_destruct;
- (void)viewDidLayoutSubviews;
- (struct UIEdgeInsets)insetsForBottomDockingView;
- (struct CGRect)defaultFrameForBottomDockingView;
- (id)bottomDockingViewForPopupBar;
- (void)updatePopup;
- (void)dismissPopupController;
- (void)presentPopupController;
- (void)dismissPopup;
- (void)presentPopup;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

