//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface UIColor (HTMLColors)
+ (id)W3CColorNames;
+ (id)colorWithW3CNamedColor:(id)arg1;
+ (id)colorWithHSLString:(id)arg1;
+ (id)colorWithRGBString:(id)arg1;
+ (id)colorWithHexString:(id)arg1;
+ (id)colorWithCSS:(id)arg1;
- (_Bool)cmr_getHue:(double *)arg1 saturation:(double *)arg2 brightness:(double *)arg3 alpha:(double *)arg4;
- (_Bool)cmr_getRed:(double *)arg1 green:(double *)arg2 blue:(double *)arg3 alpha:(double *)arg4;
- (id)hslStringValue;
- (id)rgbStringValue;
- (id)hexStringValue;
@end

