//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIDevice.h"

@interface UIDevice (Private)
- (_Bool)jailbroken;
- (id)_uniqueIdentifierUUID;
- (id)_kernOSRelease;
- (id)_kernOSType;
- (id)_platform;
- (id)_uniqueIdentifier;
@end

