//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

@interface UINavigationController (LNPopupSupportPrivate)
+ (void)load;
- (void)_ln_setNavigationBarHidden:(_Bool)arg1 animated:(_Bool)arg2;
- (id)_ln_childViewControllerForStatusBarStyle;
- (id)_ln_childViewControllerForStatusBarHidden;
- (void)hSNBDS:(id)arg1 f:(id)arg2 c:(id)arg3;
- (struct UIEdgeInsets)eIFCVC:(id)arg1 iAA:(_Bool *)arg2;
- (void)_sTH:(_Bool)arg1 e:(unsigned int)arg2 d:(double)arg3;
- (void)_uLFSBAIO;
- (id)_aSTVC;
- (struct CGRect)defaultFrameForBottomDockingView;
- (id)bottomDockingViewForPopupBar;
- (id)bottomDockingViewForPopup_nocreate;
@end

