//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITabBarController.h"

@interface UITabBarController (LNPopupSupportPrivate)
+ (void)load;
- (id)_ln_childViewControllerForStatusBarStyle;
- (id)_ln_childViewControllerForStatusBarHidden;
- (void)sBWT:(long long)arg1 iE:(_Bool)arg2;
- (void)hBWT:(long long)arg1 iE:(_Bool)arg2;
- (void)__repositionPopupBarToClosed_hack;
- (struct UIEdgeInsets)eIFCVC:(id)arg1 iAA:(_Bool *)arg2;
- (void)_uLFSBAIO;
- (id)_aSTVC;
- (struct CGRect)defaultFrameForBottomDockingView;
- (struct UIEdgeInsets)insetsForBottomDockingView;
- (id)bottomDockingViewForPopupBar;
- (id)bottomDockingViewForPopup_nocreate;
- (void)_setTabBarHiddenDuringTransition:(_Bool)arg1;
- (_Bool)_isTabBarHiddenDuringTransition;
@end

