//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (LNCustomContainerPopupSupport)
- (struct CGRect)defaultFrameForBottomDockingView_internalOrDeveloper;
- (struct CGRect)defaultFrameForBottomDockingView_internal;
- (struct CGRect)defaultFrameForBottomDockingView;
- (struct UIEdgeInsets)insetsForBottomDockingView;
- (id)bottomDockingViewForPopupBar;
- (id)bottomDockingViewForPopup_internalOrDeveloper;
- (id)bottomDockingViewForPopup_nocreateOrDeveloper;
- (id)_ln_bottomBarSupport;
- (id)_ln_bottomBarSupport_nocreate;
- (id)_ln_popupController;
@end

