//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (LNPopupLayout)
+ (void)load;
- (void)_setIgnoringLayoutDuringTransition:(_Bool)arg1;
- (_Bool)_ignoringLayoutDuringTransition;
- (void)_ln_popup_viewDidLayoutSubviews;
- (void)_layoutPopupBarOrderForUse;
- (void)_layoutPopupBarOrderForTransition;
- (_Bool)_vCUSB;
- (struct UIEdgeInsets)_ln_common_eIFCVC:(id)arg1 iAA:(_Bool *)arg2;
- (struct UIEdgeInsets)_vSAIFS;
- (void)_sCoOvIns:(struct UIEdgeInsets)arg1;
- (void)_uLFSBAIO;
- (void)_common_uLFSBAIO;
- (id)_aSTVC;
- (id)_ln_childViewControllerForStatusBarStyle;
- (id)_ln_childViewControllerForStatusBarHidden;
- (id)_ln_common_childViewControllerForStatusBarStyle;
- (id)_ln_common_childViewControllerForStatusBarHidden;
- (id)_common_childviewControllersForStatusBarLogic;
- (id)_findChildInPopupPresentation;
- (id)_findAncestorParentPopupContainerController;
- (void)_ln_willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2;
- (void)_ln_viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)_ln_setNeedsStatusBarAppearanceUpdate;
- (void)_ln_presentViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_ln_sPVC:(id)arg1;
- (struct UIEdgeInsets)_ln_popupSafeAreaInsetsForChildController;
- (struct UIEdgeInsets)_ln_additionalSafeAreaInsets;
- (void)_ln_setAdditionalSafeAreaInsets:(struct UIEdgeInsets)arg1;
@end

