//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class LNPopupController, _LNPopupBottomBarSupport;

@interface UIViewController (LNPopupSupportPrivate)

// Remaining properties
@property(readonly, nonatomic, getter=_ln_bottomBarSupport) _LNPopupBottomBarSupport *bottomBarSupport; // @dynamic bottomBarSupport;
@property(readonly, nonatomic, getter=_ln_popupController) LNPopupController *ln_popupController; // @dynamic ln_popupController;
@property(readonly, nonatomic) UIViewController *popupContentViewController; // @dynamic popupContentViewController;
@property(nonatomic) UIViewController *popupPresentationContainerViewController; // @dynamic popupPresentationContainerViewController;
@end

