//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (LNPopupSupport)
- (void)setPopupBarPreviewingDelegate:(id)arg1;
- (id)popupBarPreviewingDelegate;
- (id)viewForPopupInteractionGestureRecognizer;
- (id)_ln_popupController_nocreate;
- (void)setPopupInteractionStyle:(unsigned long long)arg1;
- (unsigned long long)popupInteractionStyle;
- (id)popupContentView;
- (id)popupBar;
- (id)popupItem;
- (void)setPopupContentViewController:(id)arg1;
- (id)popupContentViewController;
- (void)setPopupPresentationContainerViewController:(id)arg1;
- (id)popupPresentationContainerViewController;
- (_Bool)_isContainedInPopupController;
- (unsigned long long)popupPresentationState;
- (void)updatePopupBarAppearance;
- (void)dismissPopupBarAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)closePopupAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)openPopupAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)presentPopupBarWithContentViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)presentPopupBarWithContentViewController:(id)arg1 openPopup:(_Bool)arg2 animated:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
@end

