//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface URLManager : NSObject
{
}

+ (id)viewControllerForURL:(id)arg1 isExternalOpen:(_Bool)arg2 presentModally:(_Bool *)arg3;
+ (id)urlRequestWithHeaders:(id)arg1 includingDeviceInfo:(_Bool)arg2;
+ (id)urlRequestWithHeaders:(id)arg1;
+ (id)urlForPackage:(id)arg1;

@end

