//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface WishListManager : NSObject
{
    NSMutableArray *_wishList;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)removePackageFromWishList:(id)arg1;
- (_Bool)addPackageToWishList:(id)arg1;
- (_Bool)isPackageInWishList:(id)arg1;
- (id)wishlist;
- (void)reloadData;
- (id)init;

@end

