//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XLFormBaseCell.h"

#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"

@class NSString, UIAlertController, UIImagePickerController;

@interface XLFormImageCell : XLFormBaseCell <UIImagePickerControllerDelegate, UINavigationControllerDelegate>
{
    UIImagePickerController *imagePickerController;
    UIAlertController *alertController;
}

+ (double)formDescriptorCellHeightForRowDescriptor:(id)arg1;
- (void).cxx_destruct;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)openImage:(long long)arg1;
- (void)formDescriptorCellDidSelectedWithFormController:(id)arg1;
- (id)imageView;
- (void)chooseImage:(id)arg1;
- (void)update;
- (void)configure;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

