//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSNumber, NSString, XLFormDescriptor, XLFormRowDescriptor;

@interface XLFormSectionDescriptor : NSObject
{
    _Bool _isDirtyHidePredicateCache;
    id _hidden;
    NSNumber *_hidePredicateCache;
    NSString *_title;
    NSString *_footerTitle;
    NSMutableArray *_formRows;
    unsigned long long _sectionInsertMode;
    unsigned long long _sectionOptions;
    XLFormRowDescriptor *_multivaluedRowTemplate;
    XLFormRowDescriptor *_multivaluedAddButton;
    NSString *_multivaluedTag;
    XLFormDescriptor *_formDescriptor;
    NSMutableArray *_allRows;
}

+ (id)formSectionWithTitle:(id)arg1 sectionOptions:(unsigned long long)arg2 sectionInsertMode:(unsigned long long)arg3;
+ (id)formSectionWithTitle:(id)arg1 sectionOptions:(unsigned long long)arg2;
+ (id)formSectionWithTitle:(id)arg1 multivaluedSection:(_Bool)arg2;
+ (id)formSectionWithTitle:(id)arg1;
+ (id)formSection;
@property(nonatomic) _Bool isDirtyHidePredicateCache; // @synthesize isDirtyHidePredicateCache=_isDirtyHidePredicateCache;
@property(retain, nonatomic) NSMutableArray *allRows; // @synthesize allRows=_allRows;
@property(nonatomic) __weak XLFormDescriptor *formDescriptor; // @synthesize formDescriptor=_formDescriptor;
@property(copy, nonatomic) NSString *multivaluedTag; // @synthesize multivaluedTag=_multivaluedTag;
@property(readonly, nonatomic) XLFormRowDescriptor *multivaluedAddButton; // @synthesize multivaluedAddButton=_multivaluedAddButton;
@property(retain, nonatomic) XLFormRowDescriptor *multivaluedRowTemplate; // @synthesize multivaluedRowTemplate=_multivaluedRowTemplate;
@property(readonly, nonatomic) unsigned long long sectionOptions; // @synthesize sectionOptions=_sectionOptions;
@property(readonly, nonatomic) unsigned long long sectionInsertMode; // @synthesize sectionInsertMode=_sectionInsertMode;
@property(retain, nonatomic) NSMutableArray *formRows; // @synthesize formRows=_formRows;
@property(copy, nonatomic) NSString *footerTitle; // @synthesize footerTitle=_footerTitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
@property(retain, nonatomic) id hidden; // @synthesize hidden=_hidden;
- (_Bool)evaluateIsHidden;
- (_Bool)isHidden;
@property(copy, nonatomic) NSNumber *hidePredicateCache; // @synthesize hidePredicateCache=_hidePredicateCache;
- (_Bool)canInsertUsingButton;
- (void)removeObjectFromAllRowsAtIndex:(unsigned long long)arg1;
- (void)insertObject:(id)arg1 inAllRowsAtIndex:(unsigned long long)arg2;
- (id)allRowsAtIndexes:(id)arg1;
- (id)objectInAllRowsAtIndex:(unsigned long long)arg1;
- (unsigned long long)countOfAllRows;
- (void)removeObjectFromFormRowsAtIndex:(unsigned long long)arg1;
- (void)insertObject:(id)arg1 inFormRowsAtIndex:(unsigned long long)arg2;
- (id)formRowsAtIndexes:(id)arg1;
- (id)objectInFormRowsAtIndex:(unsigned long long)arg1;
- (unsigned long long)countOfFormRows;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)hideFormRow:(id)arg1;
- (void)showFormRow:(id)arg1;
- (void)dealloc;
- (void)moveRowAtIndexPath:(id)arg1 toIndexPath:(id)arg2;
- (void)removeFormRow:(id)arg1;
- (void)removeFormRowAtIndex:(unsigned long long)arg1;
- (void)addFormRow:(id)arg1 beforeRow:(id)arg2;
- (void)addFormRow:(id)arg1 afterRow:(id)arg2;
- (void)addFormRow:(id)arg1;
- (_Bool)isMultivaluedSection;
- (id)initWithTitle:(id)arg1 sectionOptions:(unsigned long long)arg2 sectionInsertMode:(unsigned long long)arg3;
- (id)init;

@end

