//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, XLFormRowDescriptor, XLFormViewController;

@protocol XLFormDescriptorCell <NSObject>
@property(nonatomic) __weak XLFormRowDescriptor *rowDescriptor;
- (void)update;
- (void)configure;

@optional
+ (double)formDescriptorCellHeightForRowDescriptor:(XLFormRowDescriptor *)arg1;
- (void)unhighlight;
- (void)highlight;
- (NSString *)formDescriptorHttpParameterName;
- (void)formDescriptorCellDidSelectedWithFormController:(XLFormViewController *)arg1;
- (_Bool)formDescriptorCellBecomeFirstResponder;
- (_Bool)formDescriptorCellCanBecomeFirstResponder;
@end

