//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface XLFormLeftRightSelectorOption : NSObject
{
    unsigned long long _leftValueChangePolicy;
    id _leftValue;
    NSArray *_rightOptions;
    NSString *_httpParameterKey;
    Class _rightSelectorControllerClass;
    NSString *_noValueDisplayText;
    NSString *_selectorTitle;
}

+ (id)formLeftRightSelectorOptionWithLeftValue:(id)arg1 httpParameterKey:(id)arg2 rightOptions:(id)arg3;
@property(copy, nonatomic) NSString *selectorTitle; // @synthesize selectorTitle=_selectorTitle;
@property(copy, nonatomic) NSString *noValueDisplayText; // @synthesize noValueDisplayText=_noValueDisplayText;
@property(retain, nonatomic) Class rightSelectorControllerClass; // @synthesize rightSelectorControllerClass=_rightSelectorControllerClass;
@property(readonly, copy, nonatomic) NSString *httpParameterKey; // @synthesize httpParameterKey=_httpParameterKey;
@property(readonly, nonatomic) NSArray *rightOptions; // @synthesize rightOptions=_rightOptions;
@property(readonly, nonatomic) id leftValue; // @synthesize leftValue=_leftValue;
@property(nonatomic) unsigned long long leftValueChangePolicy; // @synthesize leftValueChangePolicy=_leftValueChangePolicy;
- (void).cxx_destruct;
- (id)initWithLeftValue:(id)arg1 httpParameterKey:(id)arg2 rightOptions:(id)arg3;

@end

