//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIToolbar.h"

@class UIBarButtonItem;

@interface XLFormRowNavigationAccessoryView : UIToolbar
{
    UIBarButtonItem *_previousButton;
    UIBarButtonItem *_nextButton;
    UIBarButtonItem *_doneButton;
}

@property(nonatomic) __weak UIBarButtonItem *doneButton; // @synthesize doneButton=_doneButton;
@property(nonatomic) __weak UIBarButtonItem *nextButton; // @synthesize nextButton=_nextButton;
@property(nonatomic) __weak UIBarButtonItem *previousButton; // @synthesize previousButton=_previousButton;
- (void).cxx_destruct;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

