//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XLFormBaseCell.h"

#import "UIPickerViewDataSource.h"
#import "UIPickerViewDelegate.h"
#import "XLFormInlineRowDescriptorCell.h"

@class NSString, UIPickerView, XLFormRowDescriptor;

@interface XLFormPickerCell : XLFormBaseCell <UIPickerViewDelegate, UIPickerViewDataSource, XLFormInlineRowDescriptorCell>
{
    UIPickerView *_pickerView;
    XLFormRowDescriptor *_inlineRowDescriptor;
}

+ (double)formDescriptorCellHeightForRowDescriptor:(id)arg1;
@property(nonatomic) __weak XLFormRowDescriptor *inlineRowDescriptor; // @synthesize inlineRowDescriptor=_inlineRowDescriptor;
@property(nonatomic) __weak UIPickerView *pickerView; // @synthesize pickerView=_pickerView;
- (void).cxx_destruct;
- (long long)selectedIndex;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (void)pickerView:(id)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3;
- (id)pickerView:(id)arg1 titleForRow:(long long)arg2 forComponent:(long long)arg3;
- (void)update;
- (void)configure;
- (_Bool)canBecomeFirstResponder;
- (_Bool)canResignFirstResponder;
- (_Bool)formDescriptorCellBecomeFirstResponder;
- (_Bool)formDescriptorCellCanBecomeFirstResponder;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) __weak XLFormRowDescriptor *rowDescriptor;
@property(readonly) Class superclass;

@end

