//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XLFormBaseCell.h"

#import "UITextViewDelegate.h"

@class NSMutableArray, NSNumber, NSString, UILabel, XLFormTextView;

@interface XLFormTextViewCell : XLFormBaseCell <UITextViewDelegate>
{
    NSMutableArray *_dynamicCustomConstraints;
    UILabel *_textLabel;
    XLFormTextView *_textView;
    NSNumber *_textViewLengthPercentage;
    NSNumber *_textViewMaxNumberOfCharacters;
}

+ (double)formDescriptorCellHeightForRowDescriptor:(id)arg1;
@property(copy, nonatomic) NSNumber *textViewMaxNumberOfCharacters; // @synthesize textViewMaxNumberOfCharacters=_textViewMaxNumberOfCharacters;
@property(copy, nonatomic) NSNumber *textViewLengthPercentage; // @synthesize textViewLengthPercentage=_textViewLengthPercentage;
@property(readonly, nonatomic) __weak XLFormTextView *textView; // @synthesize textView=_textView;
@property(readonly, nonatomic) __weak UILabel *textLabel; // @synthesize textLabel=_textLabel;
- (void).cxx_destruct;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidChange:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)updateConstraints;
- (void)unhighlight;
- (void)highlight;
- (_Bool)formDescriptorCellBecomeFirstResponder;
- (_Bool)formDescriptorCellCanBecomeFirstResponder;
- (void)update;
- (void)configure;
@property(readonly, nonatomic) UILabel *label;
- (void)dealloc;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

