//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSArray, NSFormatter, NSMutableArray, NSMutableDictionary, NSNumber, NSString, XLFormAction, XLFormBaseCell, XLFormSectionDescriptor;

@interface XLFormRowDescriptor : NSObject <NSCopying>
{
    _Bool _useValueFormatterDuringInput;
    _Bool _required;
    _Bool _isDirtyDisablePredicateCache;
    _Bool _isDirtyHidePredicateCache;
    XLFormAction *_action;
    id _disabled;
    id _hidden;
    NSNumber *_hidePredicateCache;
    NSNumber *_disablePredicateCache;
    NSMutableDictionary *_cellConfig;
    NSMutableDictionary *_cellConfigForSelector;
    NSMutableDictionary *_cellConfigIfDisabled;
    NSMutableDictionary *_cellConfigAtConfigure;
    double _height;
    id _cellClass;
    NSString *_tag;
    NSString *_rowType;
    NSString *_title;
    id _value;
    Class _valueTransformer;
    long long _cellStyle;
    CDUnknownBlockType _onChangeBlock;
    NSFormatter *_valueFormatter;
    XLFormSectionDescriptor *_sectionDescriptor;
    NSString *_requireMsg;
    NSString *_noValueDisplayText;
    NSString *_selectorTitle;
    NSArray *_selectorOptions;
    id _leftRightSelectorLeftOptionSelected;
    XLFormBaseCell *_cell;
    NSMutableArray *_validators;
}

+ (id)formRowDescriptorWithTag:(id)arg1 rowType:(id)arg2 title:(id)arg3;
+ (id)formRowDescriptorWithTag:(id)arg1 rowType:(id)arg2;
@property(nonatomic) _Bool isDirtyHidePredicateCache; // @synthesize isDirtyHidePredicateCache=_isDirtyHidePredicateCache;
@property(nonatomic) _Bool isDirtyDisablePredicateCache; // @synthesize isDirtyDisablePredicateCache=_isDirtyDisablePredicateCache;
@property(retain, nonatomic) NSMutableArray *validators; // @synthesize validators=_validators;
@property(retain, nonatomic) XLFormBaseCell *cell; // @synthesize cell=_cell;
@property(retain) id leftRightSelectorLeftOptionSelected; // @synthesize leftRightSelectorLeftOptionSelected=_leftRightSelectorLeftOptionSelected;
@property(retain, nonatomic) NSArray *selectorOptions; // @synthesize selectorOptions=_selectorOptions;
@property(copy, nonatomic) NSString *selectorTitle; // @synthesize selectorTitle=_selectorTitle;
@property(copy, nonatomic) NSString *noValueDisplayText; // @synthesize noValueDisplayText=_noValueDisplayText;
@property(copy, nonatomic) NSString *requireMsg; // @synthesize requireMsg=_requireMsg;
@property(nonatomic) __weak XLFormSectionDescriptor *sectionDescriptor; // @synthesize sectionDescriptor=_sectionDescriptor;
@property(nonatomic, getter=isRequired) _Bool required; // @synthesize required=_required;
@property(retain, nonatomic) NSFormatter *valueFormatter; // @synthesize valueFormatter=_valueFormatter;
@property(nonatomic) _Bool useValueFormatterDuringInput; // @synthesize useValueFormatterDuringInput=_useValueFormatterDuringInput;
@property(copy, nonatomic) CDUnknownBlockType onChangeBlock; // @synthesize onChangeBlock=_onChangeBlock;
@property(nonatomic) long long cellStyle; // @synthesize cellStyle=_cellStyle;
@property(retain, nonatomic) Class valueTransformer; // @synthesize valueTransformer=_valueTransformer;
@property(retain, nonatomic) id value; // @synthesize value=_value;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, copy, nonatomic) NSString *rowType; // @synthesize rowType=_rowType;
@property(copy, nonatomic) NSString *tag; // @synthesize tag=_tag;
@property(retain, nonatomic) id cellClass; // @synthesize cellClass=_cellClass;
- (void).cxx_destruct;
@property unsigned long long buttonViewControllerPresentationMode;
@property(retain) Class selectorControllerClass;
@property(retain) Class buttonViewController;
- (id)doValidation;
- (_Bool)valueIsEmpty;
- (void)removeValidator:(id)arg1;
- (void)addValidator:(id)arg1;
@property(retain, nonatomic) id hidden; // @synthesize hidden=_hidden;
- (_Bool)evaluateIsHidden;
- (_Bool)isHidden;
@property(copy, nonatomic) NSNumber *hidePredicateCache; // @synthesize hidePredicateCache=_hidePredicateCache;
@property(copy, nonatomic) NSNumber *disablePredicateCache; // @synthesize disablePredicateCache=_disablePredicateCache;
@property(retain, nonatomic) id disabled; // @synthesize disabled=_disabled;
- (_Bool)evaluateIsDisabled;
- (_Bool)isDisabled;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(nonatomic) double height; // @synthesize height=_height;
@property(retain, nonatomic) XLFormAction *action; // @synthesize action=_action;
- (id)description;
- (id)displayTextValue;
- (id)editTextValue;
@property(readonly, nonatomic) NSMutableDictionary *cellConfigAtConfigure; // @synthesize cellConfigAtConfigure=_cellConfigAtConfigure;
@property(readonly, nonatomic) NSMutableDictionary *cellConfigIfDisabled; // @synthesize cellConfigIfDisabled=_cellConfigIfDisabled;
@property(readonly, nonatomic) NSMutableDictionary *cellConfigForSelector; // @synthesize cellConfigForSelector=_cellConfigForSelector;
@property(readonly, nonatomic) NSMutableDictionary *cellConfig; // @synthesize cellConfig=_cellConfig;
- (void)configureCellAtCreationTime;
- (id)cellForFormController:(id)arg1;
- (id)initWithTag:(id)arg1 rowType:(id)arg2 title:(id)arg3;
- (id)init;

@end

