//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "XLFormOptionObject.h"

@class NSString;

@interface XLFormOptionsObject : NSObject <XLFormOptionObject, NSCoding>
{
    NSString *_formDisplaytext;
    id _formValue;
}

+ (id)formOptionsOptionForDisplayText:(id)arg1 fromOptions:(id)arg2;
+ (id)formOptionsOptionForValue:(id)arg1 fromOptions:(id)arg2;
+ (id)formOptionsObjectWithValue:(id)arg1 displayText:(id)arg2;
@property(retain, nonatomic) id formValue; // @synthesize formValue=_formValue;
@property(copy, nonatomic) NSString *formDisplaytext; // @synthesize formDisplaytext=_formDisplaytext;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)formDisplayText;
- (_Bool)isEqual:(id)arg1;
- (id)initWithValue:(id)arg1 displayText:(id)arg2;

@end

