//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XLFormValidator.h"

@class NSString;

@interface XLFormRegexValidator : XLFormValidator
{
    NSString *_msg;
    NSString *_regex;
}

+ (id)formRegexValidatorWithMsg:(id)arg1 regex:(id)arg2;
@property(copy, nonatomic) NSString *regex; // @synthesize regex=_regex;
@property(copy, nonatomic) NSString *msg; // @synthesize msg=_msg;
- (void).cxx_destruct;
- (id)isValid:(id)arg1;
- (id)initWithMsg:(id)arg1 andRegexString:(id)arg2;

@end

