//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, XLFormRowDescriptor;

@interface XLFormValidationStatus : NSObject
{
    _Bool _isValid;
    NSString *_msg;
    XLFormRowDescriptor *_rowDescriptor;
}

+ (id)formValidationStatusWithMsg:(id)arg1 status:(_Bool)arg2 rowDescriptor:(id)arg3;
+ (id)formValidationStatusWithMsg:(id)arg1 status:(_Bool)arg2;
@property(nonatomic) __weak XLFormRowDescriptor *rowDescriptor; // @synthesize rowDescriptor=_rowDescriptor;
@property(nonatomic) _Bool isValid; // @synthesize isValid=_isValid;
@property(copy, nonatomic) NSString *msg; // @synthesize msg=_msg;
- (void).cxx_destruct;
- (id)initWithMsg:(id)arg1 status:(_Bool)arg2 rowDescriptor:(id)arg3;
- (id)initWithMsg:(id)arg1 andStatus:(_Bool)arg2;

@end

