//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XLFormBaseCell.h"

@interface XLFormButtonCell : XLFormBaseCell
{
}

- (id)storyboardToPresent;
- (id)controllerToPresent;
- (void)formDescriptorCellDidSelectedWithFormController:(id)arg1;
- (void)update;
- (void)configure;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

