//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class XLFormRowDescriptor, XLFormValidationStatus;

@protocol XLFormValidatorProtocol <NSObject>
- (XLFormValidationStatus *)isValid:(XLFormRowDescriptor *)arg1;
@end

